package com.cip.transactions;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="AccountingTypeData")
public class AccountingTypeData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private Integer AccountingTypeID;
    @XmlElement
    private GLTData AssetClass;
    @XmlElement
    private String CalendarCode;
    @XmlElement
    private Integer CouponDateID;
    @XmlElement
    private Integer DaysToSettle;
    @XmlElement
    private String Name;
    @XmlElement
    private Integer PayFreq;
    @XmlElement
    private Integer QTYPrecision;
    @XmlElement
    private Integer Status;

    public AccountingTypeData() {
    }
    
    public AccountingTypeData(Integer Status, Integer CouponDateID, Integer PayFreq, Integer AccountingTypeID, String CalendarCode, Integer DaysToSettle, Integer QTYPrecision, GLTData AssetClass, String Name) {
        this.Status = Status;
        this.CouponDateID = CouponDateID;
        this.PayFreq = PayFreq;
        this.AccountingTypeID = AccountingTypeID;
        this.CalendarCode = CalendarCode;
        this.DaysToSettle = DaysToSettle;
        this.QTYPrecision = QTYPrecision;
        this.AssetClass = AssetClass;
        this.Name = Name;
    }
    
    public AccountingTypeData(String Name, Integer Status, Integer PayFreq, Integer DaysToSettle, Integer CouponDateID, GLTData AssetClass, Integer AccountingTypeID, Integer QTYPrecision, String CalendarCode) {
        this.Name = Name;
        this.Status = Status;
        this.PayFreq = PayFreq;
        this.DaysToSettle = DaysToSettle;
        this.CouponDateID = CouponDateID;
        this.AssetClass = AssetClass;
        this.AccountingTypeID = AccountingTypeID;
        this.QTYPrecision = QTYPrecision;
        this.CalendarCode = CalendarCode;
    }

    public Integer getAccountingTypeID() {
        return this.AccountingTypeID;
    }
    
    public void setAccountingTypeID(Integer AccountingTypeID) {
        this.AccountingTypeID = AccountingTypeID;
    }

    public GLTData getAssetClass() {
        return this.AssetClass;
    }
    
    public void setAssetClass(GLTData AssetClass) {
        this.AssetClass = AssetClass;
    }

    public String getCalendarCode() {
        return this.CalendarCode;
    }
    
    public void setCalendarCode(String CalendarCode) {
        this.CalendarCode = CalendarCode;
    }

    public Integer getCouponDateID() {
        return this.CouponDateID;
    }
    
    public void setCouponDateID(Integer CouponDateID) {
        this.CouponDateID = CouponDateID;
    }

    public Integer getDaysToSettle() {
        return this.DaysToSettle;
    }
    
    public void setDaysToSettle(Integer DaysToSettle) {
        this.DaysToSettle = DaysToSettle;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    public Integer getPayFreq() {
        return this.PayFreq;
    }
    
    public void setPayFreq(Integer PayFreq) {
        this.PayFreq = PayFreq;
    }

    public Integer getQTYPrecision() {
        return this.QTYPrecision;
    }
    
    public void setQTYPrecision(Integer QTYPrecision) {
        this.QTYPrecision = QTYPrecision;
    }

    public Integer getStatus() {
        return this.Status;
    }
    
    public void setStatus(Integer Status) {
        this.Status = Status;
    }

}