package com.cip.transactions;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="AssetData")
public class AssetData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private Integer AccountingTypeID;
    @XmlElement
    private BigDecimal AccruedInt;
    @XmlElement
    private BigDecimal AnnualIncome;
    @XmlElement
    private Integer AssetID;
    @XmlElement
    private AssetLVRData AssetLVR;
    @XmlElement
    private AssetTypeData AssetType;
    @XmlElement
    private String CCYCode;
    @XmlElement
    private String CCYName;
    @XmlElement
    private String CUSIP;
    @XmlElement
    private String Certificated;
    @XmlElement
    private String Code;
    @XmlElement
    private CountryData Country;
    @XmlElement
    private Integer CouponFreq;
    @XmlElement
    private BigDecimal CouponRate;
    @XmlElement
    private CurrencyData Currency;
    @XmlElement
    private Integer DaysToSettle;
    @XmlElement
    private DataProviderData DefaultDataProvider;
    @XmlElement
    private DataProviderData DefaultPriceProvider;
    @XmlElement
    private DataProviderData DefaultPriceSource;
    @XmlElement
    private String Description;
    @XmlElement
    private BigDecimal Duration;
    @XmlElement
    private ExchangeData Exchange;
    @XmlElement
    private String Fungible;
    @XmlElement
    private AssetData FungibleAsset;
    @XmlElement
    private String FungibleAssetStr;
    @XmlElement
    private String ISIN;
    @XmlElement
    private String ISINISO;
    @XmlElement
    private CountryData IncomeCountry;
    @XmlElement
    private Boolean IsEquity;
    @XmlElement
    private Boolean IsFixedDeposit;
    @XmlElement
    private Boolean IsFixedIncome;
    @XmlElement
    private Boolean IsLendingCash;
    @XmlElement
    private Boolean IsMutualFund;
    @XmlElement
    private Boolean IsProperty;
    @XmlElement
    private IssueData Issue;
    @XmlElement
    private BigDecimal MaturityPrice;
    @XmlElement
    private BigDecimal MinLotSize;
    @XmlElement
    private String Name;
    @XmlElement
    private Integer NominalPrecision;
    @XmlElement
    private Integer OptionStyleID;
    @XmlElement
    private Integer OptionTypeID;
    @XmlElement
    private String PriceClean;
    @XmlElement
    private Integer PriceCurrency;
    @XmlElement
    private DataProviderData PriceProvider;
    @XmlElement
    private String PrimaryListing;
    @XmlElement
    private BigDecimal QTYPrecision;
    @XmlElement
    private String RIC;
    @XmlElement
    private OrganisationData Registrar;
    @XmlElement
    private String ReportingType;
    @XmlElement
    private String SEDOL;
    @XmlElement
    private Integer SecurityID;
    @XmlElement
    private AssetTypeData SecurityType;
    @XmlElement
    private SourceCategoryData SourceCategory;
    @XmlElement
    private Integer Status;
    @XmlElement
    private String TaxSource;
    @XmlElement
    private String Type;
    @XmlElement
    private Integer UnderlyingSecurityID;
    @XmlElement
    private BigDecimal UnitPriceFactor;
    @XmlElement
    private BigDecimal UnitSize;
    @XmlElement
    private BigDecimal YieldToMaturity;
    @XmlElement
    private Boolean isCash;
    @XmlElement
    private Boolean isTypeB;
    @XmlElement
    private Boolean isTypeDeposit;

    public AssetData() {
    }
    
    public AssetData(IssueData Issue, String CCYName, String ReportingType, DataProviderData PriceProvider, Integer NominalPrecision, AssetData FungibleAsset, Boolean isTypeDeposit, String Name, DataProviderData DefaultPriceProvider, CurrencyData Currency, String Certificated, String CCYCode, Integer Status, String TaxSource, AssetLVRData AssetLVR, DataProviderData DefaultPriceSource, BigDecimal Duration, BigDecimal UnitSize, String Code, String PriceClean, ExchangeData Exchange, BigDecimal MaturityPrice, Integer AccountingTypeID, BigDecimal UnitPriceFactor, Integer OptionTypeID, CountryData Country, Boolean isTypeB, BigDecimal QTYPrecision, String SEDOL, Integer PriceCurrency, Integer UnderlyingSecurityID, AssetTypeData SecurityType, String Description, String ISINISO, Boolean IsFixedDeposit, CountryData IncomeCountry, String CUSIP, String FungibleAssetStr, OrganisationData Registrar, Integer DaysToSettle, BigDecimal MinLotSize, Integer SecurityID, Boolean isCash, SourceCategoryData SourceCategory, Integer AssetID, Boolean IsEquity, BigDecimal CouponRate, String Fungible, Boolean IsProperty, Boolean IsLendingCash, Boolean IsFixedIncome, String RIC, String ISIN, BigDecimal AccruedInt, AssetTypeData AssetType, String Type, String PrimaryListing, BigDecimal YieldToMaturity, DataProviderData DefaultDataProvider, Boolean IsMutualFund, BigDecimal AnnualIncome, Integer CouponFreq, Integer OptionStyleID) {
        this.Issue = Issue;
        this.CCYName = CCYName;
        this.ReportingType = ReportingType;
        this.PriceProvider = PriceProvider;
        this.NominalPrecision = NominalPrecision;
        this.FungibleAsset = FungibleAsset;
        this.isTypeDeposit = isTypeDeposit;
        this.Name = Name;
        this.DefaultPriceProvider = DefaultPriceProvider;
        this.Currency = Currency;
        this.Certificated = Certificated;
        this.CCYCode = CCYCode;
        this.Status = Status;
        this.TaxSource = TaxSource;
        this.AssetLVR = AssetLVR;
        this.DefaultPriceSource = DefaultPriceSource;
        this.Duration = Duration;
        this.UnitSize = UnitSize;
        this.Code = Code;
        this.PriceClean = PriceClean;
        this.Exchange = Exchange;
        this.MaturityPrice = MaturityPrice;
        this.AccountingTypeID = AccountingTypeID;
        this.UnitPriceFactor = UnitPriceFactor;
        this.OptionTypeID = OptionTypeID;
        this.Country = Country;
        this.isTypeB = isTypeB;
        this.QTYPrecision = QTYPrecision;
        this.SEDOL = SEDOL;
        this.PriceCurrency = PriceCurrency;
        this.UnderlyingSecurityID = UnderlyingSecurityID;
        this.SecurityType = SecurityType;
        this.Description = Description;
        this.ISINISO = ISINISO;
        this.IsFixedDeposit = IsFixedDeposit;
        this.IncomeCountry = IncomeCountry;
        this.CUSIP = CUSIP;
        this.FungibleAssetStr = FungibleAssetStr;
        this.Registrar = Registrar;
        this.DaysToSettle = DaysToSettle;
        this.MinLotSize = MinLotSize;
        this.SecurityID = SecurityID;
        this.isCash = isCash;
        this.SourceCategory = SourceCategory;
        this.AssetID = AssetID;
        this.IsEquity = IsEquity;
        this.CouponRate = CouponRate;
        this.Fungible = Fungible;
        this.IsProperty = IsProperty;
        this.IsLendingCash = IsLendingCash;
        this.IsFixedIncome = IsFixedIncome;
        this.RIC = RIC;
        this.ISIN = ISIN;
        this.AccruedInt = AccruedInt;
        this.AssetType = AssetType;
        this.Type = Type;
        this.PrimaryListing = PrimaryListing;
        this.YieldToMaturity = YieldToMaturity;
        this.DefaultDataProvider = DefaultDataProvider;
        this.IsMutualFund = IsMutualFund;
        this.AnnualIncome = AnnualIncome;
        this.CouponFreq = CouponFreq;
        this.OptionStyleID = OptionStyleID;
    }
    
    public AssetData(String Fungible, BigDecimal UnitSize, Boolean IsEquity, Boolean IsProperty, BigDecimal QTYPrecision, String Certificated, Boolean IsLendingCash, String FungibleAssetStr, String ISINISO, Boolean IsFixedIncome, AssetTypeData SecurityType, Integer AccountingTypeID, Boolean IsFixedDeposit, Integer SecurityID, SourceCategoryData SourceCategory, Boolean IsMutualFund, OrganisationData Registrar, String TaxSource, Boolean isCash, String CCYCode, AssetTypeData AssetType, BigDecimal AnnualIncome, DataProviderData DefaultDataProvider, BigDecimal CouponRate, IssueData Issue, String SEDOL, DataProviderData DefaultPriceSource, CurrencyData Currency, Boolean isTypeB, Boolean isTypeDeposit, String CCYName, BigDecimal AccruedInt, CountryData Country, String CUSIP, BigDecimal UnitPriceFactor, String ReportingType, String Type, Integer DaysToSettle, String RIC, AssetLVRData AssetLVR, String Code, BigDecimal MinLotSize, ExchangeData Exchange, Integer NominalPrecision, BigDecimal Duration, DataProviderData DefaultPriceProvider, Integer AssetID, String Description, BigDecimal YieldToMaturity, Integer PriceCurrency, DataProviderData PriceProvider, String ISIN, Integer CouponFreq, String Name, Integer Status, BigDecimal MaturityPrice, Integer OptionStyleID, Integer OptionTypeID, Integer UnderlyingSecurityID, String PriceClean, CountryData IncomeCountry, AssetData FungibleAsset, String PrimaryListing) {
        this.Fungible = Fungible;
        this.UnitSize = UnitSize;
        this.IsEquity = IsEquity;
        this.IsProperty = IsProperty;
        this.QTYPrecision = QTYPrecision;
        this.Certificated = Certificated;
        this.IsLendingCash = IsLendingCash;
        this.FungibleAssetStr = FungibleAssetStr;
        this.ISINISO = ISINISO;
        this.IsFixedIncome = IsFixedIncome;
        this.SecurityType = SecurityType;
        this.AccountingTypeID = AccountingTypeID;
        this.IsFixedDeposit = IsFixedDeposit;
        this.SecurityID = SecurityID;
        this.SourceCategory = SourceCategory;
        this.IsMutualFund = IsMutualFund;
        this.Registrar = Registrar;
        this.TaxSource = TaxSource;
        this.isCash = isCash;
        this.CCYCode = CCYCode;
        this.AssetType = AssetType;
        this.AnnualIncome = AnnualIncome;
        this.DefaultDataProvider = DefaultDataProvider;
        this.CouponRate = CouponRate;
        this.Issue = Issue;
        this.SEDOL = SEDOL;
        this.DefaultPriceSource = DefaultPriceSource;
        this.Currency = Currency;
        this.isTypeB = isTypeB;
        this.isTypeDeposit = isTypeDeposit;
        this.CCYName = CCYName;
        this.AccruedInt = AccruedInt;
        this.Country = Country;
        this.CUSIP = CUSIP;
        this.UnitPriceFactor = UnitPriceFactor;
        this.ReportingType = ReportingType;
        this.Type = Type;
        this.DaysToSettle = DaysToSettle;
        this.RIC = RIC;
        this.AssetLVR = AssetLVR;
        this.Code = Code;
        this.MinLotSize = MinLotSize;
        this.Exchange = Exchange;
        this.NominalPrecision = NominalPrecision;
        this.Duration = Duration;
        this.DefaultPriceProvider = DefaultPriceProvider;
        this.AssetID = AssetID;
        this.Description = Description;
        this.YieldToMaturity = YieldToMaturity;
        this.PriceCurrency = PriceCurrency;
        this.PriceProvider = PriceProvider;
        this.ISIN = ISIN;
        this.CouponFreq = CouponFreq;
        this.Name = Name;
        this.Status = Status;
        this.MaturityPrice = MaturityPrice;
        this.OptionStyleID = OptionStyleID;
        this.OptionTypeID = OptionTypeID;
        this.UnderlyingSecurityID = UnderlyingSecurityID;
        this.PriceClean = PriceClean;
        this.IncomeCountry = IncomeCountry;
        this.FungibleAsset = FungibleAsset;
        this.PrimaryListing = PrimaryListing;
    }

    public Integer getAccountingTypeID() {
        return this.AccountingTypeID;
    }
    
    public void setAccountingTypeID(Integer AccountingTypeID) {
        this.AccountingTypeID = AccountingTypeID;
    }

    public BigDecimal getAccruedInt() {
        return this.AccruedInt;
    }
    
    public void setAccruedInt(BigDecimal AccruedInt) {
        this.AccruedInt = AccruedInt;
    }

    public BigDecimal getAnnualIncome() {
        return this.AnnualIncome;
    }
    
    public void setAnnualIncome(BigDecimal AnnualIncome) {
        this.AnnualIncome = AnnualIncome;
    }

    public Integer getAssetID() {
        return this.AssetID;
    }
    
    public void setAssetID(Integer AssetID) {
        this.AssetID = AssetID;
    }

    public AssetLVRData getAssetLVR() {
        return this.AssetLVR;
    }
    
    public void setAssetLVR(AssetLVRData AssetLVR) {
        this.AssetLVR = AssetLVR;
    }

    public AssetTypeData getAssetType() {
        return this.AssetType;
    }
    
    public void setAssetType(AssetTypeData AssetType) {
        this.AssetType = AssetType;
    }

    public String getCCYCode() {
        return this.CCYCode;
    }
    
    public void setCCYCode(String CCYCode) {
        this.CCYCode = CCYCode;
    }

    public String getCCYName() {
        return this.CCYName;
    }
    
    public void setCCYName(String CCYName) {
        this.CCYName = CCYName;
    }

    public String getCUSIP() {
        return this.CUSIP;
    }
    
    public void setCUSIP(String CUSIP) {
        this.CUSIP = CUSIP;
    }

    public String getCertificated() {
        return this.Certificated;
    }
    
    public void setCertificated(String Certificated) {
        this.Certificated = Certificated;
    }

    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    public CountryData getCountry() {
        return this.Country;
    }
    
    public void setCountry(CountryData Country) {
        this.Country = Country;
    }

    public Integer getCouponFreq() {
        return this.CouponFreq;
    }
    
    public void setCouponFreq(Integer CouponFreq) {
        this.CouponFreq = CouponFreq;
    }

    public BigDecimal getCouponRate() {
        return this.CouponRate;
    }
    
    public void setCouponRate(BigDecimal CouponRate) {
        this.CouponRate = CouponRate;
    }

    public CurrencyData getCurrency() {
        return this.Currency;
    }
    
    public void setCurrency(CurrencyData Currency) {
        this.Currency = Currency;
    }

    public Integer getDaysToSettle() {
        return this.DaysToSettle;
    }
    
    public void setDaysToSettle(Integer DaysToSettle) {
        this.DaysToSettle = DaysToSettle;
    }

    public DataProviderData getDefaultDataProvider() {
        return this.DefaultDataProvider;
    }
    
    public void setDefaultDataProvider(DataProviderData DefaultDataProvider) {
        this.DefaultDataProvider = DefaultDataProvider;
    }

    public DataProviderData getDefaultPriceProvider() {
        return this.DefaultPriceProvider;
    }
    
    public void setDefaultPriceProvider(DataProviderData DefaultPriceProvider) {
        this.DefaultPriceProvider = DefaultPriceProvider;
    }

    public DataProviderData getDefaultPriceSource() {
        return this.DefaultPriceSource;
    }
    
    public void setDefaultPriceSource(DataProviderData DefaultPriceSource) {
        this.DefaultPriceSource = DefaultPriceSource;
    }

    public String getDescription() {
        return this.Description;
    }
    
    public void setDescription(String Description) {
        this.Description = Description;
    }

    public BigDecimal getDuration() {
        return this.Duration;
    }
    
    public void setDuration(BigDecimal Duration) {
        this.Duration = Duration;
    }

    public ExchangeData getExchange() {
        return this.Exchange;
    }
    
    public void setExchange(ExchangeData Exchange) {
        this.Exchange = Exchange;
    }

    public String getFungible() {
        return this.Fungible;
    }
    
    public void setFungible(String Fungible) {
        this.Fungible = Fungible;
    }

    public AssetData getFungibleAsset() {
        return this.FungibleAsset;
    }
    
    public void setFungibleAsset(AssetData FungibleAsset) {
        this.FungibleAsset = FungibleAsset;
    }

    public String getFungibleAssetStr() {
        return this.FungibleAssetStr;
    }
    
    public void setFungibleAssetStr(String FungibleAssetStr) {
        this.FungibleAssetStr = FungibleAssetStr;
    }

    public String getISIN() {
        return this.ISIN;
    }
    
    public void setISIN(String ISIN) {
        this.ISIN = ISIN;
    }

    public String getISINISO() {
        return this.ISINISO;
    }
    
    public void setISINISO(String ISINISO) {
        this.ISINISO = ISINISO;
    }

    public CountryData getIncomeCountry() {
        return this.IncomeCountry;
    }
    
    public void setIncomeCountry(CountryData IncomeCountry) {
        this.IncomeCountry = IncomeCountry;
    }

    public Boolean getIsEquity() {
        return this.IsEquity;
    }
    
    public void setIsEquity(Boolean IsEquity) {
        this.IsEquity = IsEquity;
    }

    public Boolean getIsFixedDeposit() {
        return this.IsFixedDeposit;
    }
    
    public void setIsFixedDeposit(Boolean IsFixedDeposit) {
        this.IsFixedDeposit = IsFixedDeposit;
    }

    public Boolean getIsFixedIncome() {
        return this.IsFixedIncome;
    }
    
    public void setIsFixedIncome(Boolean IsFixedIncome) {
        this.IsFixedIncome = IsFixedIncome;
    }

    public Boolean getIsLendingCash() {
        return this.IsLendingCash;
    }
    
    public void setIsLendingCash(Boolean IsLendingCash) {
        this.IsLendingCash = IsLendingCash;
    }

    public Boolean getIsMutualFund() {
        return this.IsMutualFund;
    }
    
    public void setIsMutualFund(Boolean IsMutualFund) {
        this.IsMutualFund = IsMutualFund;
    }

    public Boolean getIsProperty() {
        return this.IsProperty;
    }
    
    public void setIsProperty(Boolean IsProperty) {
        this.IsProperty = IsProperty;
    }

    public IssueData getIssue() {
        return this.Issue;
    }
    
    public void setIssue(IssueData Issue) {
        this.Issue = Issue;
    }

    public BigDecimal getMaturityPrice() {
        return this.MaturityPrice;
    }
    
    public void setMaturityPrice(BigDecimal MaturityPrice) {
        this.MaturityPrice = MaturityPrice;
    }

    public BigDecimal getMinLotSize() {
        return this.MinLotSize;
    }
    
    public void setMinLotSize(BigDecimal MinLotSize) {
        this.MinLotSize = MinLotSize;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    public Integer getNominalPrecision() {
        return this.NominalPrecision;
    }
    
    public void setNominalPrecision(Integer NominalPrecision) {
        this.NominalPrecision = NominalPrecision;
    }

    public Integer getOptionStyleID() {
        return this.OptionStyleID;
    }
    
    public void setOptionStyleID(Integer OptionStyleID) {
        this.OptionStyleID = OptionStyleID;
    }

    public Integer getOptionTypeID() {
        return this.OptionTypeID;
    }
    
    public void setOptionTypeID(Integer OptionTypeID) {
        this.OptionTypeID = OptionTypeID;
    }

    public String getPriceClean() {
        return this.PriceClean;
    }
    
    public void setPriceClean(String PriceClean) {
        this.PriceClean = PriceClean;
    }

    public Integer getPriceCurrency() {
        return this.PriceCurrency;
    }
    
    public void setPriceCurrency(Integer PriceCurrency) {
        this.PriceCurrency = PriceCurrency;
    }

    public DataProviderData getPriceProvider() {
        return this.PriceProvider;
    }
    
    public void setPriceProvider(DataProviderData PriceProvider) {
        this.PriceProvider = PriceProvider;
    }

    public String getPrimaryListing() {
        return this.PrimaryListing;
    }
    
    public void setPrimaryListing(String PrimaryListing) {
        this.PrimaryListing = PrimaryListing;
    }

    public BigDecimal getQTYPrecision() {
        return this.QTYPrecision;
    }
    
    public void setQTYPrecision(BigDecimal QTYPrecision) {
        this.QTYPrecision = QTYPrecision;
    }

    public String getRIC() {
        return this.RIC;
    }
    
    public void setRIC(String RIC) {
        this.RIC = RIC;
    }

    public OrganisationData getRegistrar() {
        return this.Registrar;
    }
    
    public void setRegistrar(OrganisationData Registrar) {
        this.Registrar = Registrar;
    }

    public String getReportingType() {
        return this.ReportingType;
    }
    
    public void setReportingType(String ReportingType) {
        this.ReportingType = ReportingType;
    }

    public String getSEDOL() {
        return this.SEDOL;
    }
    
    public void setSEDOL(String SEDOL) {
        this.SEDOL = SEDOL;
    }

    public Integer getSecurityID() {
        return this.SecurityID;
    }
    
    public void setSecurityID(Integer SecurityID) {
        this.SecurityID = SecurityID;
    }

    public AssetTypeData getSecurityType() {
        return this.SecurityType;
    }
    
    public void setSecurityType(AssetTypeData SecurityType) {
        this.SecurityType = SecurityType;
    }

    public SourceCategoryData getSourceCategory() {
        return this.SourceCategory;
    }
    
    public void setSourceCategory(SourceCategoryData SourceCategory) {
        this.SourceCategory = SourceCategory;
    }

    public Integer getStatus() {
        return this.Status;
    }
    
    public void setStatus(Integer Status) {
        this.Status = Status;
    }

    public String getTaxSource() {
        return this.TaxSource;
    }
    
    public void setTaxSource(String TaxSource) {
        this.TaxSource = TaxSource;
    }

    public String getType() {
        return this.Type;
    }
    
    public void setType(String Type) {
        this.Type = Type;
    }

    public Integer getUnderlyingSecurityID() {
        return this.UnderlyingSecurityID;
    }
    
    public void setUnderlyingSecurityID(Integer UnderlyingSecurityID) {
        this.UnderlyingSecurityID = UnderlyingSecurityID;
    }

    public BigDecimal getUnitPriceFactor() {
        return this.UnitPriceFactor;
    }
    
    public void setUnitPriceFactor(BigDecimal UnitPriceFactor) {
        this.UnitPriceFactor = UnitPriceFactor;
    }

    public BigDecimal getUnitSize() {
        return this.UnitSize;
    }
    
    public void setUnitSize(BigDecimal UnitSize) {
        this.UnitSize = UnitSize;
    }

    public BigDecimal getYieldToMaturity() {
        return this.YieldToMaturity;
    }
    
    public void setYieldToMaturity(BigDecimal YieldToMaturity) {
        this.YieldToMaturity = YieldToMaturity;
    }

    public Boolean getIsCash() {
        return this.isCash;
    }
    
    public void setIsCash(Boolean isCash) {
        this.isCash = isCash;
    }

    public Boolean getIsTypeB() {
        return this.isTypeB;
    }
    
    public void setIsTypeB(Boolean isTypeB) {
        this.isTypeB = isTypeB;
    }

    public Boolean getIsTypeDeposit() {
        return this.isTypeDeposit;
    }
    
    public void setIsTypeDeposit(Boolean isTypeDeposit) {
        this.isTypeDeposit = isTypeDeposit;
    }

}