package com.cip.transactions;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="AssetLVRData")
public class AssetLVRData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private Integer AssetLVRID;
    @XmlElement
    private BigDecimal LVRValue;

    public AssetLVRData() {
    }
    
    public AssetLVRData(BigDecimal LVRValue, Integer AssetLVRID) {
        this.LVRValue = LVRValue;
        this.AssetLVRID = AssetLVRID;
    }

    public Integer getAssetLVRID() {
        return this.AssetLVRID;
    }
    
    public void setAssetLVRID(Integer AssetLVRID) {
        this.AssetLVRID = AssetLVRID;
    }

    public BigDecimal getLVRValue() {
        return this.LVRValue;
    }
    
    public void setLVRValue(BigDecimal LVRValue) {
        this.LVRValue = LVRValue;
    }

}