package com.cip.transactions;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="AssetTypeData")
public class AssetTypeData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private AccountingTypeData AccountingTypeData;
    @XmlElement
    private Integer AssetTypeID;
    @XmlElement
    private GLTData InvestmentType;
    @XmlElement
    private BigDecimal MinLotSize;
    @XmlElement
    private String Name;
    @XmlElement
    private Integer NominalPrecision;
    @XmlElement
    private Integer QTYPrecision;
    @XmlElement
    private Integer SecurityTypeID;
    @XmlElement
    private BigDecimal UnitPriceFactor;
    @XmlElement
    private BigDecimal UnitSize;
    @XmlElement
    private Boolean isBond;
    @XmlElement
    private Boolean isCD;
    @XmlElement
    private Boolean isCPaper;
    @XmlElement
    private Boolean isCash;
    @XmlElement
    private Boolean isDeposit;
    @XmlElement
    private Boolean isEquity;
    @XmlElement
    private Boolean isFXOption;
    @XmlElement
    private Boolean isFixedIncome;
    @XmlElement
    private Boolean isFuture;
    @XmlElement
    private Boolean isLendingCash;
    @XmlElement
    private Boolean isOption;
    @XmlElement
    private Boolean isRepo;
    @XmlElement
    private Boolean isTBill;
    @XmlElement
    private Boolean isWarrant;

    public AssetTypeData() {
    }
    
    public AssetTypeData(Boolean isCPaper, Integer NominalPrecision, Boolean isFixedIncome, Boolean isOption, Boolean isLendingCash, Boolean isWarrant, Boolean isBond, Boolean isDeposit, BigDecimal UnitSize, AccountingTypeData AccountingTypeData, Integer AssetTypeID, String Name, Boolean isFuture, GLTData InvestmentType, Integer SecurityTypeID, Boolean isFXOption, Boolean isRepo, BigDecimal MinLotSize, BigDecimal UnitPriceFactor, Boolean isEquity, Boolean isCD, Integer QTYPrecision, Boolean isTBill, Boolean isCash) {
        this.isCPaper = isCPaper;
        this.NominalPrecision = NominalPrecision;
        this.isFixedIncome = isFixedIncome;
        this.isOption = isOption;
        this.isLendingCash = isLendingCash;
        this.isWarrant = isWarrant;
        this.isBond = isBond;
        this.isDeposit = isDeposit;
        this.UnitSize = UnitSize;
        this.AccountingTypeData = AccountingTypeData;
        this.AssetTypeID = AssetTypeID;
        this.Name = Name;
        this.isFuture = isFuture;
        this.InvestmentType = InvestmentType;
        this.SecurityTypeID = SecurityTypeID;
        this.isFXOption = isFXOption;
        this.isRepo = isRepo;
        this.MinLotSize = MinLotSize;
        this.UnitPriceFactor = UnitPriceFactor;
        this.isEquity = isEquity;
        this.isCD = isCD;
        this.QTYPrecision = QTYPrecision;
        this.isTBill = isTBill;
        this.isCash = isCash;
    }
    
    public AssetTypeData(Boolean isRepo, Integer SecurityTypeID, Boolean isBond, AccountingTypeData AccountingTypeData, Boolean isCPaper, Boolean isLendingCash, Boolean isFixedIncome, Integer AssetTypeID, Boolean isDeposit, BigDecimal UnitSize, Integer QTYPrecision, String Name, BigDecimal MinLotSize, Boolean isCash, Integer NominalPrecision, Boolean isTBill, BigDecimal UnitPriceFactor, GLTData InvestmentType, Boolean isFXOption, Boolean isEquity, Boolean isFuture, Boolean isCD, Boolean isOption, Boolean isWarrant) {
        this.isRepo = isRepo;
        this.SecurityTypeID = SecurityTypeID;
        this.isBond = isBond;
        this.AccountingTypeData = AccountingTypeData;
        this.isCPaper = isCPaper;
        this.isLendingCash = isLendingCash;
        this.isFixedIncome = isFixedIncome;
        this.AssetTypeID = AssetTypeID;
        this.isDeposit = isDeposit;
        this.UnitSize = UnitSize;
        this.QTYPrecision = QTYPrecision;
        this.Name = Name;
        this.MinLotSize = MinLotSize;
        this.isCash = isCash;
        this.NominalPrecision = NominalPrecision;
        this.isTBill = isTBill;
        this.UnitPriceFactor = UnitPriceFactor;
        this.InvestmentType = InvestmentType;
        this.isFXOption = isFXOption;
        this.isEquity = isEquity;
        this.isFuture = isFuture;
        this.isCD = isCD;
        this.isOption = isOption;
        this.isWarrant = isWarrant;
    }

    public AccountingTypeData getAccountingTypeData() {
        return this.AccountingTypeData;
    }
    
    public void setAccountingTypeData(AccountingTypeData AccountingTypeData) {
        this.AccountingTypeData = AccountingTypeData;
    }

    public Integer getAssetTypeID() {
        return this.AssetTypeID;
    }
    
    public void setAssetTypeID(Integer AssetTypeID) {
        this.AssetTypeID = AssetTypeID;
    }

    public GLTData getInvestmentType() {
        return this.InvestmentType;
    }
    
    public void setInvestmentType(GLTData InvestmentType) {
        this.InvestmentType = InvestmentType;
    }

    public BigDecimal getMinLotSize() {
        return this.MinLotSize;
    }
    
    public void setMinLotSize(BigDecimal MinLotSize) {
        this.MinLotSize = MinLotSize;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    public Integer getNominalPrecision() {
        return this.NominalPrecision;
    }
    
    public void setNominalPrecision(Integer NominalPrecision) {
        this.NominalPrecision = NominalPrecision;
    }

    public Integer getQTYPrecision() {
        return this.QTYPrecision;
    }
    
    public void setQTYPrecision(Integer QTYPrecision) {
        this.QTYPrecision = QTYPrecision;
    }

    public Integer getSecurityTypeID() {
        return this.SecurityTypeID;
    }
    
    public void setSecurityTypeID(Integer SecurityTypeID) {
        this.SecurityTypeID = SecurityTypeID;
    }

    public BigDecimal getUnitPriceFactor() {
        return this.UnitPriceFactor;
    }
    
    public void setUnitPriceFactor(BigDecimal UnitPriceFactor) {
        this.UnitPriceFactor = UnitPriceFactor;
    }

    public BigDecimal getUnitSize() {
        return this.UnitSize;
    }
    
    public void setUnitSize(BigDecimal UnitSize) {
        this.UnitSize = UnitSize;
    }

    public Boolean getIsBond() {
        return this.isBond;
    }
    
    public void setIsBond(Boolean isBond) {
        this.isBond = isBond;
    }

    public Boolean getIsCD() {
        return this.isCD;
    }
    
    public void setIsCD(Boolean isCD) {
        this.isCD = isCD;
    }

    public Boolean getIsCPaper() {
        return this.isCPaper;
    }
    
    public void setIsCPaper(Boolean isCPaper) {
        this.isCPaper = isCPaper;
    }

    public Boolean getIsCash() {
        return this.isCash;
    }
    
    public void setIsCash(Boolean isCash) {
        this.isCash = isCash;
    }

    public Boolean getIsDeposit() {
        return this.isDeposit;
    }
    
    public void setIsDeposit(Boolean isDeposit) {
        this.isDeposit = isDeposit;
    }

    public Boolean getIsEquity() {
        return this.isEquity;
    }
    
    public void setIsEquity(Boolean isEquity) {
        this.isEquity = isEquity;
    }

    public Boolean getIsFXOption() {
        return this.isFXOption;
    }
    
    public void setIsFXOption(Boolean isFXOption) {
        this.isFXOption = isFXOption;
    }

    public Boolean getIsFixedIncome() {
        return this.isFixedIncome;
    }
    
    public void setIsFixedIncome(Boolean isFixedIncome) {
        this.isFixedIncome = isFixedIncome;
    }

    public Boolean getIsFuture() {
        return this.isFuture;
    }
    
    public void setIsFuture(Boolean isFuture) {
        this.isFuture = isFuture;
    }

    public Boolean getIsLendingCash() {
        return this.isLendingCash;
    }
    
    public void setIsLendingCash(Boolean isLendingCash) {
        this.isLendingCash = isLendingCash;
    }

    public Boolean getIsOption() {
        return this.isOption;
    }
    
    public void setIsOption(Boolean isOption) {
        this.isOption = isOption;
    }

    public Boolean getIsRepo() {
        return this.isRepo;
    }
    
    public void setIsRepo(Boolean isRepo) {
        this.isRepo = isRepo;
    }

    public Boolean getIsTBill() {
        return this.isTBill;
    }
    
    public void setIsTBill(Boolean isTBill) {
        this.isTBill = isTBill;
    }

    public Boolean getIsWarrant() {
        return this.isWarrant;
    }
    
    public void setIsWarrant(Boolean isWarrant) {
        this.isWarrant = isWarrant;
    }

}