package com.cip.transactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="BusinessProcess")
public class BusinessProcess implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private String Code;
    @XmlElement
    private String Function;
    @XmlElement
    private String Name;

    public BusinessProcess() {
    }
    
    public BusinessProcess(String Function, String Code, String Name) {
        this.Function = Function;
        this.Code = Code;
        this.Name = Name;
    }

    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    public String getFunction() {
        return this.Function;
    }
    
    public void setFunction(String Function) {
        this.Function = Function;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

}