package com.cip.transactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="ClientData")
public class ClientData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private GLTData AccountType;
    @XmlElement
    private String AccountTypeCode;
    @XmlElement
    private Integer AccountTypeID;
    @XmlElement
    private GLTData AdviceLevel;
    @XmlElement
    private Integer AdviceLevelID;
    @XmlElement
    private Integer AuditID;
    @XmlElement
    private String Branch;
    @XmlElement
    private Integer ClientID;
    @XmlElement
    private String Code;
    @XmlElement
    private AddressData CompanyReportAddress;
    @XmlElement
    private CountryData Country;
    @XmlElement
    private Integer CountryID;
    @XmlElement
    private CurrencyData Currency;
    @XmlElement
    private Integer CurrencyID;
    @XmlElement
    private Integer DRUMID;
    @XmlElement
    private Integer DRUMPK;
    @XmlElement
    private GLTData DRUMRole;
    @XmlElement
    private Integer DRUMRoleID;
    @XmlElement
    private GLTData DRUMStatus;
    @XmlElement
    private Integer DRUMStatusID;
    @XmlElement
    private DataProviderData DataProvider;
    @XmlElement
    private Integer DataProviderID;
    @XmlElement
    private AddressData DefaultAddress;
    @XmlElement
    private String DefaultReportGrouping;
    @XmlElement
    private String DeflatableClass;
    @XmlElement
    private String DeflatedRoleNames;
    @XmlElement
    private String EMail;
    @XmlElement
    private AddressData ElectiveCorpActionAddress;
    @XmlElement
    private AddressData EmailAddress;
    @XmlElement
    private Boolean Flag;
    @XmlElement
    private Boolean Ide;
    @XmlElement
    private Boolean IsAce;
    @XmlElement
    private Boolean IsActive;
    @XmlElement
    private String IsAmended;
    @XmlElement
    private Boolean IsCashman;
    @XmlElement
    private Boolean IsClientOverrideAssetRoute;
    @XmlElement
    private Boolean IsCompanyReport;
    @XmlElement
    private Boolean IsDeflated;
    @XmlElement
    private Boolean IsEquities;
    @XmlElement
    private Boolean IsIde;
    @XmlElement
    private Boolean IsLending;
    @XmlElement
    private Boolean IsNameChange;
    @XmlElement
    private Boolean IsOneOff;
    @XmlElement
    private Boolean IsPortfolioClient;
    @XmlElement
    private Boolean IsProxyVotingStatus;
    @XmlElement
    private Boolean IsUnitInvesting;
    @XmlElement
    private String LongName;
    @XmlElement
    private String Name;
    @XmlElement
    private GLTData OptOut;
    @XmlElement
    private Integer OptOutID;
    @XmlElement
    private String OriginalName;
    @XmlElement
    private String PFClient;
    @XmlElement
    private String Phone;
    @XmlElement
    private java.math.BigDecimal PieRate;
    @XmlElement
    private String ProxyVotingStatus;
    @XmlElement
    private Integer SystemID;
    @XmlElement
    private String UCode;
    @XmlElement
    private String UName;
    @XmlElement
    private Integer Version;
    @XmlElement
    private String When;
    @XmlElement
    private String Who;

    public ClientData() {
    }
    
    public ClientData(Integer CountryID, String DeflatedRoleNames, Boolean IsDeflated, Integer AdviceLevelID, String IsAmended, Integer SystemID, Boolean Ide, Boolean IsPortfolioClient, Integer DRUMStatusID, String Name, Integer AccountTypeID, AddressData CompanyReportAddress, GLTData OptOut, Boolean IsClientOverrideAssetRoute, Integer Version, Integer DRUMPK, CurrencyData Currency, Boolean IsUnitInvesting, GLTData DRUMStatus, String Who, Boolean IsNameChange, GLTData AdviceLevel, Boolean IsEquities, Boolean IsProxyVotingStatus, String PFClient, String OriginalName, String Code, Boolean Flag, AddressData EmailAddress, String UCode, Integer OptOutID, String ProxyVotingStatus, String AccountTypeCode, String DeflatableClass, Integer ClientID, CountryData Country, java.math.BigDecimal PieRate, Boolean IsIde, Boolean IsOneOff, AddressData DefaultAddress, GLTData DRUMRole, String DefaultReportGrouping, Boolean IsActive, DataProviderData DataProvider, String UName, String Phone, String Branch, Integer AuditID, Boolean IsCompanyReport, Boolean IsAce, Boolean IsCashman, String EMail, GLTData AccountType, Integer CurrencyID, AddressData ElectiveCorpActionAddress, Boolean IsLending, String When, String LongName, Integer DRUMID, Integer DataProviderID, Integer DRUMRoleID) {
        this.CountryID = CountryID;
        this.DeflatedRoleNames = DeflatedRoleNames;
        this.IsDeflated = IsDeflated;
        this.AdviceLevelID = AdviceLevelID;
        this.IsAmended = IsAmended;
        this.SystemID = SystemID;
        this.Ide = Ide;
        this.IsPortfolioClient = IsPortfolioClient;
        this.DRUMStatusID = DRUMStatusID;
        this.Name = Name;
        this.AccountTypeID = AccountTypeID;
        this.CompanyReportAddress = CompanyReportAddress;
        this.OptOut = OptOut;
        this.IsClientOverrideAssetRoute = IsClientOverrideAssetRoute;
        this.Version = Version;
        this.DRUMPK = DRUMPK;
        this.Currency = Currency;
        this.IsUnitInvesting = IsUnitInvesting;
        this.DRUMStatus = DRUMStatus;
        this.Who = Who;
        this.IsNameChange = IsNameChange;
        this.AdviceLevel = AdviceLevel;
        this.IsEquities = IsEquities;
        this.IsProxyVotingStatus = IsProxyVotingStatus;
        this.PFClient = PFClient;
        this.OriginalName = OriginalName;
        this.Code = Code;
        this.Flag = Flag;
        this.EmailAddress = EmailAddress;
        this.UCode = UCode;
        this.OptOutID = OptOutID;
        this.ProxyVotingStatus = ProxyVotingStatus;
        this.AccountTypeCode = AccountTypeCode;
        this.DeflatableClass = DeflatableClass;
        this.ClientID = ClientID;
        this.Country = Country;
        this.PieRate = PieRate;
        this.IsIde = IsIde;
        this.IsOneOff = IsOneOff;
        this.DefaultAddress = DefaultAddress;
        this.DRUMRole = DRUMRole;
        this.DefaultReportGrouping = DefaultReportGrouping;
        this.IsActive = IsActive;
        this.DataProvider = DataProvider;
        this.UName = UName;
        this.Phone = Phone;
        this.Branch = Branch;
        this.AuditID = AuditID;
        this.IsCompanyReport = IsCompanyReport;
        this.IsAce = IsAce;
        this.IsCashman = IsCashman;
        this.EMail = EMail;
        this.AccountType = AccountType;
        this.CurrencyID = CurrencyID;
        this.ElectiveCorpActionAddress = ElectiveCorpActionAddress;
        this.IsLending = IsLending;
        this.When = When;
        this.LongName = LongName;
        this.DRUMID = DRUMID;
        this.DataProviderID = DataProviderID;
        this.DRUMRoleID = DRUMRoleID;
    }
    
    public ClientData(Integer AdviceLevelID, Boolean IsOneOff, String PFClient, GLTData AdviceLevel, Integer ClientID, Integer AccountTypeID, AddressData CompanyReportAddress, Boolean IsPortfolioClient, GLTData AccountType, String ProxyVotingStatus, String Phone, String Branch, String EMail, Integer SystemID, Integer DataProviderID, String LongName, String Code, String Who, Integer DRUMID, AddressData EmailAddress, Integer CountryID, Integer Version, CurrencyData Currency, DataProviderData DataProvider, Boolean IsIde, GLTData DRUMRole, Boolean Flag, Integer CurrencyID, CountryData Country, String When, AddressData DefaultAddress, String Name, Integer DRUMStatusID, GLTData DRUMStatus, Integer DRUMRoleID, String AccountTypeCode, String UCode, String OriginalName, Boolean IsNameChange, Boolean IsActive, Boolean IsDeflated, String DeflatableClass, String DeflatedRoleNames, String UName, Integer DRUMPK, Boolean IsCashman, Boolean IsLending, Boolean IsAce, GLTData OptOut, Integer OptOutID, java.math.BigDecimal PieRate, AddressData ElectiveCorpActionAddress, Boolean IsUnitInvesting, Boolean IsEquities, Boolean IsCompanyReport, Boolean IsProxyVotingStatus, String IsAmended, Integer AuditID, String DefaultReportGrouping, Boolean Ide, Boolean IsClientOverrideAssetRoute) {
        this.AdviceLevelID = AdviceLevelID;
        this.IsOneOff = IsOneOff;
        this.PFClient = PFClient;
        this.AdviceLevel = AdviceLevel;
        this.ClientID = ClientID;
        this.AccountTypeID = AccountTypeID;
        this.CompanyReportAddress = CompanyReportAddress;
        this.IsPortfolioClient = IsPortfolioClient;
        this.AccountType = AccountType;
        this.ProxyVotingStatus = ProxyVotingStatus;
        this.Phone = Phone;
        this.Branch = Branch;
        this.EMail = EMail;
        this.SystemID = SystemID;
        this.DataProviderID = DataProviderID;
        this.LongName = LongName;
        this.Code = Code;
        this.Who = Who;
        this.DRUMID = DRUMID;
        this.EmailAddress = EmailAddress;
        this.CountryID = CountryID;
        this.Version = Version;
        this.Currency = Currency;
        this.DataProvider = DataProvider;
        this.IsIde = IsIde;
        this.DRUMRole = DRUMRole;
        this.Flag = Flag;
        this.CurrencyID = CurrencyID;
        this.Country = Country;
        this.When = When;
        this.DefaultAddress = DefaultAddress;
        this.Name = Name;
        this.DRUMStatusID = DRUMStatusID;
        this.DRUMStatus = DRUMStatus;
        this.DRUMRoleID = DRUMRoleID;
        this.AccountTypeCode = AccountTypeCode;
        this.UCode = UCode;
        this.OriginalName = OriginalName;
        this.IsNameChange = IsNameChange;
        this.IsActive = IsActive;
        this.IsDeflated = IsDeflated;
        this.DeflatableClass = DeflatableClass;
        this.DeflatedRoleNames = DeflatedRoleNames;
        this.UName = UName;
        this.DRUMPK = DRUMPK;
        this.IsCashman = IsCashman;
        this.IsLending = IsLending;
        this.IsAce = IsAce;
        this.OptOut = OptOut;
        this.OptOutID = OptOutID;
        this.PieRate = PieRate;
        this.ElectiveCorpActionAddress = ElectiveCorpActionAddress;
        this.IsUnitInvesting = IsUnitInvesting;
        this.IsEquities = IsEquities;
        this.IsCompanyReport = IsCompanyReport;
        this.IsProxyVotingStatus = IsProxyVotingStatus;
        this.IsAmended = IsAmended;
        this.AuditID = AuditID;
        this.DefaultReportGrouping = DefaultReportGrouping;
        this.Ide = Ide;
        this.IsClientOverrideAssetRoute = IsClientOverrideAssetRoute;
    }

    public GLTData getAccountType() {
        return this.AccountType;
    }
    
    public void setAccountType(GLTData AccountType) {
        this.AccountType = AccountType;
    }

    public String getAccountTypeCode() {
        return this.AccountTypeCode;
    }
    
    public void setAccountTypeCode(String AccountTypeCode) {
        this.AccountTypeCode = AccountTypeCode;
    }

    public Integer getAccountTypeID() {
        return this.AccountTypeID;
    }
    
    public void setAccountTypeID(Integer AccountTypeID) {
        this.AccountTypeID = AccountTypeID;
    }

    public GLTData getAdviceLevel() {
        return this.AdviceLevel;
    }
    
    public void setAdviceLevel(GLTData AdviceLevel) {
        this.AdviceLevel = AdviceLevel;
    }

    public Integer getAdviceLevelID() {
        return this.AdviceLevelID;
    }
    
    public void setAdviceLevelID(Integer AdviceLevelID) {
        this.AdviceLevelID = AdviceLevelID;
    }

    public Integer getAuditID() {
        return this.AuditID;
    }
    
    public void setAuditID(Integer AuditID) {
        this.AuditID = AuditID;
    }

    public String getBranch() {
        return this.Branch;
    }
    
    public void setBranch(String Branch) {
        this.Branch = Branch;
    }

    public Integer getClientID() {
        return this.ClientID;
    }
    
    public void setClientID(Integer ClientID) {
        this.ClientID = ClientID;
    }

    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    public AddressData getCompanyReportAddress() {
        return this.CompanyReportAddress;
    }
    
    public void setCompanyReportAddress(AddressData CompanyReportAddress) {
        this.CompanyReportAddress = CompanyReportAddress;
    }

    public CountryData getCountry() {
        return this.Country;
    }
    
    public void setCountry(CountryData Country) {
        this.Country = Country;
    }

    public Integer getCountryID() {
        return this.CountryID;
    }
    
    public void setCountryID(Integer CountryID) {
        this.CountryID = CountryID;
    }

    public CurrencyData getCurrency() {
        return this.Currency;
    }
    
    public void setCurrency(CurrencyData Currency) {
        this.Currency = Currency;
    }

    public Integer getCurrencyID() {
        return this.CurrencyID;
    }
    
    public void setCurrencyID(Integer CurrencyID) {
        this.CurrencyID = CurrencyID;
    }

    public Integer getDRUMID() {
        return this.DRUMID;
    }
    
    public void setDRUMID(Integer DRUMID) {
        this.DRUMID = DRUMID;
    }

    public Integer getDRUMPK() {
        return this.DRUMPK;
    }
    
    public void setDRUMPK(Integer DRUMPK) {
        this.DRUMPK = DRUMPK;
    }

    public GLTData getDRUMRole() {
        return this.DRUMRole;
    }
    
    public void setDRUMRole(GLTData DRUMRole) {
        this.DRUMRole = DRUMRole;
    }

    public Integer getDRUMRoleID() {
        return this.DRUMRoleID;
    }
    
    public void setDRUMRoleID(Integer DRUMRoleID) {
        this.DRUMRoleID = DRUMRoleID;
    }

    public GLTData getDRUMStatus() {
        return this.DRUMStatus;
    }
    
    public void setDRUMStatus(GLTData DRUMStatus) {
        this.DRUMStatus = DRUMStatus;
    }

    public Integer getDRUMStatusID() {
        return this.DRUMStatusID;
    }
    
    public void setDRUMStatusID(Integer DRUMStatusID) {
        this.DRUMStatusID = DRUMStatusID;
    }

    public DataProviderData getDataProvider() {
        return this.DataProvider;
    }
    
    public void setDataProvider(DataProviderData DataProvider) {
        this.DataProvider = DataProvider;
    }

    public Integer getDataProviderID() {
        return this.DataProviderID;
    }
    
    public void setDataProviderID(Integer DataProviderID) {
        this.DataProviderID = DataProviderID;
    }

    public AddressData getDefaultAddress() {
        return this.DefaultAddress;
    }
    
    public void setDefaultAddress(AddressData DefaultAddress) {
        this.DefaultAddress = DefaultAddress;
    }

    public String getDefaultReportGrouping() {
        return this.DefaultReportGrouping;
    }
    
    public void setDefaultReportGrouping(String DefaultReportGrouping) {
        this.DefaultReportGrouping = DefaultReportGrouping;
    }

    public String getDeflatableClass() {
        return this.DeflatableClass;
    }
    
    public void setDeflatableClass(String DeflatableClass) {
        this.DeflatableClass = DeflatableClass;
    }

    public String getDeflatedRoleNames() {
        return this.DeflatedRoleNames;
    }
    
    public void setDeflatedRoleNames(String DeflatedRoleNames) {
        this.DeflatedRoleNames = DeflatedRoleNames;
    }

    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }

    public AddressData getElectiveCorpActionAddress() {
        return this.ElectiveCorpActionAddress;
    }
    
    public void setElectiveCorpActionAddress(AddressData ElectiveCorpActionAddress) {
        this.ElectiveCorpActionAddress = ElectiveCorpActionAddress;
    }

    public AddressData getEmailAddress() {
        return this.EmailAddress;
    }
    
    public void setEmailAddress(AddressData EmailAddress) {
        this.EmailAddress = EmailAddress;
    }

    
    public Boolean getFlag() {
        return this.Flag;
    }
    
    public void setFlag(Boolean Flag) {
        this.Flag = Flag;
    }

    public Boolean getIde() {
        return this.Ide;
    }
    
    public void setIde(Boolean Ide) {
        this.Ide = Ide;
    }

    public Boolean getIsAce() {
        return this.IsAce;
    }
    
    public void setIsAce(Boolean IsAce) {
        this.IsAce = IsAce;
    }

    public Boolean getIsActive() {
        return this.IsActive;
    }
    
    public void setIsActive(Boolean IsActive) {
        this.IsActive = IsActive;
    }

    public String getIsAmended() {
        return this.IsAmended;
    }
    
    public void setIsAmended(String IsAmended) {
        this.IsAmended = IsAmended;
    }

    public Boolean getIsCashman() {
        return this.IsCashman;
    }
    
    public void setIsCashman(Boolean IsCashman) {
        this.IsCashman = IsCashman;
    }

    public Boolean getIsClientOverrideAssetRoute() {
        return this.IsClientOverrideAssetRoute;
    }
    
    public void setIsClientOverrideAssetRoute(Boolean IsClientOverrideAssetRoute) {
        this.IsClientOverrideAssetRoute = IsClientOverrideAssetRoute;
    }

    public Boolean getIsCompanyReport() {
        return this.IsCompanyReport;
    }
    
    public void setIsCompanyReport(Boolean IsCompanyReport) {
        this.IsCompanyReport = IsCompanyReport;
    }

    public Boolean getIsDeflated() {
        return this.IsDeflated;
    }
    
    public void setIsDeflated(Boolean IsDeflated) {
        this.IsDeflated = IsDeflated;
    }

    public Boolean getIsEquities() {
        return this.IsEquities;
    }
    
    public void setIsEquities(Boolean IsEquities) {
        this.IsEquities = IsEquities;
    }

    public Boolean getIsIde() {
        return this.IsIde;
    }
    
    public void setIsIde(Boolean IsIde) {
        this.IsIde = IsIde;
    }

    public Boolean getIsLending() {
        return this.IsLending;
    }
    
    public void setIsLending(Boolean IsLending) {
        this.IsLending = IsLending;
    }

    public Boolean getIsNameChange() {
        return this.IsNameChange;
    }
    
    public void setIsNameChange(Boolean IsNameChange) {
        this.IsNameChange = IsNameChange;
    }

    public Boolean getIsOneOff() {
        return this.IsOneOff;
    }
    
    public void setIsOneOff(Boolean IsOneOff) {
        this.IsOneOff = IsOneOff;
    }

    public Boolean getIsPortfolioClient() {
        return this.IsPortfolioClient;
    }
    
    public void setIsPortfolioClient(Boolean IsPortfolioClient) {
        this.IsPortfolioClient = IsPortfolioClient;
    }

    public Boolean getIsProxyVotingStatus() {
        return this.IsProxyVotingStatus;
    }
    
    public void setIsProxyVotingStatus(Boolean IsProxyVotingStatus) {
        this.IsProxyVotingStatus = IsProxyVotingStatus;
    }

    public Boolean getIsUnitInvesting() {
        return this.IsUnitInvesting;
    }
    
    public void setIsUnitInvesting(Boolean IsUnitInvesting) {
        this.IsUnitInvesting = IsUnitInvesting;
    }

    public String getLongName() {
        return this.LongName;
    }
    
    public void setLongName(String LongName) {
        this.LongName = LongName;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    public GLTData getOptOut() {
        return this.OptOut;
    }
    
    public void setOptOut(GLTData OptOut) {
        this.OptOut = OptOut;
    }

    public Integer getOptOutID() {
        return this.OptOutID;
    }
    
    public void setOptOutID(Integer OptOutID) {
        this.OptOutID = OptOutID;
    }

    public String getOriginalName() {
        return this.OriginalName;
    }
    
    public void setOriginalName(String OriginalName) {
        this.OriginalName = OriginalName;
    }

    public String getPFClient() {
        return this.PFClient;
    }
    
    public void setPFClient(String PFClient) {
        this.PFClient = PFClient;
    }

    public String getPhone() {
        return this.Phone;
    }
    
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    public java.math.BigDecimal getPieRate() {
        return this.PieRate;
    }
    
    public void setPieRate(java.math.BigDecimal PieRate) {
        this.PieRate = PieRate;
    }

    public String getProxyVotingStatus() {
        return this.ProxyVotingStatus;
    }
    
    public void setProxyVotingStatus(String ProxyVotingStatus) {
        this.ProxyVotingStatus = ProxyVotingStatus;
    }

    public Integer getSystemID() {
        return this.SystemID;
    }
    
    public void setSystemID(Integer SystemID) {
        this.SystemID = SystemID;
    }

    public String getUCode() {
        return this.UCode;
    }
    
    public void setUCode(String UCode) {
        this.UCode = UCode;
    }

    public String getUName() {
        return this.UName;
    }
    
    public void setUName(String UName) {
        this.UName = UName;
    }

    public Integer getVersion() {
        return this.Version;
    }
    
    public void setVersion(Integer Version) {
        this.Version = Version;
    }

    public String getWhen() {
        return this.When;
    }
    
    public void setWhen(String When) {
        this.When = When;
    }

    public String getWho() {
        return this.Who;
    }
    
    public void setWho(String Who) {
        this.Who = Who;
    }

}