package com.cip.transactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="CountryData")
public class CountryData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private String ColourCode;
    @XmlElement
    private Integer CountryID;
    @XmlElement
    private String ISOCode;
    @XmlElement
    private String Name;
    @XmlElement
    private Integer SortOrder;
    @XmlElement
    private Integer Status;

    public CountryData() {
    }
    
    public CountryData(Integer Status, String ISOCode, Integer CountryID, Integer SortOrder, String ColourCode, String Name) {
        this.Status = Status;
        this.ISOCode = ISOCode;
        this.CountryID = CountryID;
        this.SortOrder = SortOrder;
        this.ColourCode = ColourCode;
        this.Name = Name;
    }
    
    public CountryData(Integer Status, String ColourCode, Integer SortOrder, String Name, String ISOCode, Integer CountryID) {
        this.Status = Status;
        this.ColourCode = ColourCode;
        this.SortOrder = SortOrder;
        this.Name = Name;
        this.ISOCode = ISOCode;
        this.CountryID = CountryID;
    }

    public String getColourCode() {
        return this.ColourCode;
    }
    
    public void setColourCode(String ColourCode) {
        this.ColourCode = ColourCode;
    }

    public Integer getCountryID() {
        return this.CountryID;
    }
    
    public void setCountryID(Integer CountryID) {
        this.CountryID = CountryID;
    }

    public String getISOCode() {
        return this.ISOCode;
    }
    
    public void setISOCode(String ISOCode) {
        this.ISOCode = ISOCode;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    public Integer getSortOrder() {
        return this.SortOrder;
    }
    
    public void setSortOrder(Integer SortOrder) {
        this.SortOrder = SortOrder;
    }

    public Integer getStatus() {
        return this.Status;
    }
    
    public void setStatus(Integer Status) {
        this.Status = Status;
    }

}