package com.cip.transactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="CurrencyData")
public class CurrencyData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private Integer CurrencyID;
    @XmlElement
    private String CurrencyUnit;
    @XmlElement
    private Integer Decimals;
    @XmlElement
    private String FractionalUnit;
    @XmlElement
    private String ISOCode;
    @XmlElement
    private String Name;
    @XmlElement
    private Integer NumberToBasic;
    @XmlElement
    private Integer SortOrder;
    @XmlElement
    private Integer Status;
    @XmlElement
    private String Symbol;

    public CurrencyData() {
    }
    
    public CurrencyData(Integer Status, String ISOCode, String CurrencyUnit, String Symbol, String FractionalUnit, Integer SortOrder, Integer Decimals, Integer CurrencyID, String Name, Integer NumberToBasic) {
        this.Status = Status;
        this.ISOCode = ISOCode;
        this.CurrencyUnit = CurrencyUnit;
        this.Symbol = Symbol;
        this.FractionalUnit = FractionalUnit;
        this.SortOrder = SortOrder;
        this.Decimals = Decimals;
        this.CurrencyID = CurrencyID;
        this.Name = Name;
        this.NumberToBasic = NumberToBasic;
    }
    
    public CurrencyData(Integer Status, String Name, Integer CurrencyID, String ISOCode, Integer Decimals, Integer SortOrder, String Symbol, String CurrencyUnit, String FractionalUnit, Integer NumberToBasic) {
        this.Status = Status;
        this.Name = Name;
        this.CurrencyID = CurrencyID;
        this.ISOCode = ISOCode;
        this.Decimals = Decimals;
        this.SortOrder = SortOrder;
        this.Symbol = Symbol;
        this.CurrencyUnit = CurrencyUnit;
        this.FractionalUnit = FractionalUnit;
        this.NumberToBasic = NumberToBasic;
    }

    public Integer getCurrencyID() {
        return this.CurrencyID;
    }
    
    public void setCurrencyID(Integer CurrencyID) {
        this.CurrencyID = CurrencyID;
    }

    public String getCurrencyUnit() {
        return this.CurrencyUnit;
    }
    
    public void setCurrencyUnit(String CurrencyUnit) {
        this.CurrencyUnit = CurrencyUnit;
    }

    public Integer getDecimals() {
        return this.Decimals;
    }
    
    public void setDecimals(Integer Decimals) {
        this.Decimals = Decimals;
    }

    public String getFractionalUnit() {
        return this.FractionalUnit;
    }
    
    public void setFractionalUnit(String FractionalUnit) {
        this.FractionalUnit = FractionalUnit;
    }

    public String getISOCode() {
        return this.ISOCode;
    }
    
    public void setISOCode(String ISOCode) {
        this.ISOCode = ISOCode;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    public Integer getNumberToBasic() {
        return this.NumberToBasic;
    }
    
    public void setNumberToBasic(Integer NumberToBasic) {
        this.NumberToBasic = NumberToBasic;
    }

    public Integer getSortOrder() {
        return this.SortOrder;
    }
    
    public void setSortOrder(Integer SortOrder) {
        this.SortOrder = SortOrder;
    }

    public Integer getStatus() {
        return this.Status;
    }
    
    public void setStatus(Integer Status) {
        this.Status = Status;
    }

    public String getSymbol() {
        return this.Symbol;
    }
    
    public void setSymbol(String Symbol) {
        this.Symbol = Symbol;
    }

}