package com.cip.transactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="DataProviderData")
public class DataProviderData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private Integer DataProviderID;
    @XmlElement
    private Integer DataProviderPK;
    @XmlElement
    private String Name;

    public DataProviderData() {
    }
    
    public DataProviderData(Integer DataProviderID, Integer DataProviderPK, String Name) {
        this.DataProviderID = DataProviderID;
        this.DataProviderPK = DataProviderPK;
        this.Name = Name;
    }
    
    public DataProviderData(String Name, Integer DataProviderID, Integer DataProviderPK) {
        this.Name = Name;
        this.DataProviderID = DataProviderID;
        this.DataProviderPK = DataProviderPK;
    }

    public Integer getDataProviderID() {
        return this.DataProviderID;
    }
    
    public void setDataProviderID(Integer DataProviderID) {
        this.DataProviderID = DataProviderID;
    }

    public Integer getDataProviderPK() {
        return this.DataProviderPK;
    }
    
    public void setDataProviderPK(Integer DataProviderPK) {
        this.DataProviderPK = DataProviderPK;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

}