package com.cip.transactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="DRUMExtCodeData")
public class DRUMExtCodeData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private String Code;
    @XmlElement
    private GLTData Type;
    @XmlElement
    private Integer drumID;

    public DRUMExtCodeData() {
    }
    
    public DRUMExtCodeData(Integer drumID, GLTData Type, String Code) {
        this.drumID = drumID;
        this.Type = Type;
        this.Code = Code;
    }

    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    public GLTData getType() {
        return this.Type;
    }
    
    public void setType(GLTData Type) {
        this.Type = Type;
    }

    public Integer getDrumID() {
        return this.drumID;
    }
    
    public void setDrumID(Integer drumID) {
        this.drumID = drumID;
    }

}