package com.cip.transactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="ErrorMessage")
public class ErrorMessage implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private Integer Code;
    @XmlElement
    private Boolean IsFatal;
    @XmlElement
    private String Message;

    public ErrorMessage() {
    }
    
    public ErrorMessage(String Message, Boolean IsFatal, Integer Code) {
        this.Message = Message;
        this.IsFatal = IsFatal;
        this.Code = Code;
    }
    
    public ErrorMessage(Integer Code, String Message, Boolean IsFatal) {
        this.Code = Code;
        this.Message = Message;
        this.IsFatal = IsFatal;
    }

    public Integer getCode() {
        return this.Code;
    }
    
    public void setCode(Integer Code) {
        this.Code = Code;
    }

    public Boolean getIsFatal() {
        return this.IsFatal;
    }
    
    public void setIsFatal(Boolean IsFatal) {
        this.IsFatal = IsFatal;
    }

    public String getMessage() {
        return this.Message;
    }
    
    public void setMessage(String Message) {
        this.Message = Message;
    }

}