package com.cip.transactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="ExchangeData")
public class ExchangeData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private String Code;
    @XmlElement
    private Integer ExchangeID;
    @XmlElement
    private String ExtCode;
    @XmlElement
    private String Name;
    @XmlElement
    private Integer Status;

    public ExchangeData() {
    }
    
    public ExchangeData(Integer Status, String ExtCode, String Code, Integer ExchangeID, String Name) {
        this.Status = Status;
        this.ExtCode = ExtCode;
        this.Code = Code;
        this.ExchangeID = ExchangeID;
        this.Name = Name;
    }

    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    public Integer getExchangeID() {
        return this.ExchangeID;
    }
    
    public void setExchangeID(Integer ExchangeID) {
        this.ExchangeID = ExchangeID;
    }

    public String getExtCode() {
        return this.ExtCode;
    }
    
    public void setExtCode(String ExtCode) {
        this.ExtCode = ExtCode;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    public Integer getStatus() {
        return this.Status;
    }
    
    public void setStatus(Integer Status) {
        this.Status = Status;
    }

}