package com.cip.transactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="GLTData")
public class GLTData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private String ClassName;
    @XmlElement
    private String Code;
    @XmlElement
    private Integer Flag;
    @XmlElement
    private Integer GLTID;
    @XmlElement
    private Integer GLTOrder;
    @XmlElement
    private String Name;
    @XmlElement
    private String SecurityGroup;
    @XmlElement
    private String SortOrder;
    @XmlElement
    private String Status;
    @XmlElement
    private String System;

    public GLTData() {
    }
    
    public GLTData(String Status, Integer GLTID, String ClassName, String SortOrder, String SecurityGroup, Integer GLTOrder, Integer Flag, String Code, String System, String Name) {
        this.Status = Status;
        this.GLTID = GLTID;
        this.ClassName = ClassName;
        this.SortOrder = SortOrder;
        this.SecurityGroup = SecurityGroup;
        this.GLTOrder = GLTOrder;
        this.Flag = Flag;
        this.Code = Code;
        this.System = System;
        this.Name = Name;
    }
    
    public GLTData(String Status, String SortOrder, String System, String Name, Integer GLTOrder, String SecurityGroup, Integer Flag, Integer GLTID, String ClassName, String Code) {
        this.Status = Status;
        this.SortOrder = SortOrder;
        this.System = System;
        this.Name = Name;
        this.GLTOrder = GLTOrder;
        this.SecurityGroup = SecurityGroup;
        this.Flag = Flag;
        this.GLTID = GLTID;
        this.ClassName = ClassName;
        this.Code = Code;
    }

    public String getClassName() {
        return this.ClassName;
    }
    
    public void setClassName(String ClassName) {
        this.ClassName = ClassName;
    }

    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    public Integer getFlag() {
        return this.Flag;
    }
    
    public void setFlag(Integer Flag) {
        this.Flag = Flag;
    }

    public Integer getGLTID() {
        return this.GLTID;
    }
    
    public void setGLTID(Integer GLTID) {
        this.GLTID = GLTID;
    }

    public Integer getGLTOrder() {
        return this.GLTOrder;
    }
    
    public void setGLTOrder(Integer GLTOrder) {
        this.GLTOrder = GLTOrder;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    public String getSecurityGroup() {
        return this.SecurityGroup;
    }
    
    public void setSecurityGroup(String SecurityGroup) {
        this.SecurityGroup = SecurityGroup;
    }

    public String getSortOrder() {
        return this.SortOrder;
    }
    
    public void setSortOrder(String SortOrder) {
        this.SortOrder = SortOrder;
    }

    public String getStatus() {
        return this.Status;
    }
    
    public void setStatus(String Status) {
        this.Status = Status;
    }

    public String getSystem() {
        return this.System;
    }
    
    public void setSystem(String System) {
        this.System = System;
    }

}