package com.cip.transactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="GroupData")
public class GroupData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private String Branch;
    @XmlElement
    private String Code;
    @XmlElement
    private CountryData Country;
    @XmlElement
    private Integer CountryID;
    @XmlElement
    private CurrencyData Currency;
    @XmlElement
    private Integer CurrencyID;
    @XmlElement
    private Integer DRUMID;
    @XmlElement
    private Integer DRUMPK;
    @XmlElement
    private GLTData DRUMRole;
    @XmlElement
    private Integer DRUMRoleID;
    @XmlElement
    private GLTData DRUMStatus;
    @XmlElement
    private Integer DRUMStatusID;
    @XmlElement
    private DataProviderData DataProvider;
    @XmlElement
    private Integer DataProviderID;
    @XmlElement
    private AddressData DefaultAddress;
    @XmlElement
    private String DeflatableClass;
    @XmlElement
    private String DeflatedRoleNames;
    @XmlElement
    private String Description;
    @XmlElement
    private String EMail;
    @XmlElement
    private AddressData EmailAddress;
    @XmlElement
    private Boolean Flag;
    @XmlElement
    private Integer GroupID;
    @XmlElement
    private GLTData GroupType;
    @XmlElement
    private Integer GroupTypeID;
    @XmlElement
    private Boolean Ide;
    @XmlElement
    private Boolean IsActive;
    @XmlElement
    private Boolean IsDeflated;
    @XmlElement
    private Boolean IsIde;
    @XmlElement
    private Boolean IsNameChange;
    @XmlElement
    private String LongName;
    @XmlElement
    private String Name;
    @XmlElement
    private String OriginalName;
    @XmlElement
    private String Phone;
    @XmlElement
    private Integer SystemID;
    @XmlElement
    private String UCode;
    @XmlElement
    private String UName;
    @XmlElement
    private Integer Version;
    @XmlElement
    private String When;
    @XmlElement
    private String Who;

    public GroupData() {
    }
    
    public GroupData(Integer CountryID, String DeflatedRoleNames, AddressData DefaultAddress, Boolean IsDeflated, GLTData DRUMRole, String Description, Boolean IsActive, Integer SystemID, Boolean Ide, Integer DRUMStatusID, Integer GroupID, String Name, DataProviderData DataProvider, String UName, Integer Version, Integer DRUMPK, String Phone, String Branch, CurrencyData Currency, GLTData DRUMStatus, String Who, Boolean IsNameChange, String OriginalName, String EMail, String Code, Boolean Flag, AddressData EmailAddress, Integer CurrencyID, String UCode, Integer GroupTypeID, String When, GLTData GroupType, String LongName, Integer DRUMID, Integer DataProviderID, String DeflatableClass, CountryData Country, Boolean IsIde, Integer DRUMRoleID) {
        this.CountryID = CountryID;
        this.DeflatedRoleNames = DeflatedRoleNames;
        this.DefaultAddress = DefaultAddress;
        this.IsDeflated = IsDeflated;
        this.DRUMRole = DRUMRole;
        this.Description = Description;
        this.IsActive = IsActive;
        this.SystemID = SystemID;
        this.Ide = Ide;
        this.DRUMStatusID = DRUMStatusID;
        this.GroupID = GroupID;
        this.Name = Name;
        this.DataProvider = DataProvider;
        this.UName = UName;
        this.Version = Version;
        this.DRUMPK = DRUMPK;
        this.Phone = Phone;
        this.Branch = Branch;
        this.Currency = Currency;
        this.DRUMStatus = DRUMStatus;
        this.Who = Who;
        this.IsNameChange = IsNameChange;
        this.OriginalName = OriginalName;
        this.EMail = EMail;
        this.Code = Code;
        this.Flag = Flag;
        this.EmailAddress = EmailAddress;
        this.CurrencyID = CurrencyID;
        this.UCode = UCode;
        this.GroupTypeID = GroupTypeID;
        this.When = When;
        this.GroupType = GroupType;
        this.LongName = LongName;
        this.DRUMID = DRUMID;
        this.DataProviderID = DataProviderID;
        this.DeflatableClass = DeflatableClass;
        this.Country = Country;
        this.IsIde = IsIde;
        this.DRUMRoleID = DRUMRoleID;
    }
    
    public GroupData(String Description, GLTData GroupType, Integer GroupID, Integer GroupTypeID, String Phone, String Branch, String EMail, Integer SystemID, Integer DataProviderID, String LongName, String Code, String Who, Integer DRUMID, AddressData EmailAddress, Integer CountryID, Integer Version, CurrencyData Currency, DataProviderData DataProvider, Boolean IsIde, GLTData DRUMRole, Boolean Flag, Integer CurrencyID, CountryData Country, String When, AddressData DefaultAddress, String Name, Integer DRUMStatusID, GLTData DRUMStatus, Integer DRUMRoleID, String UCode, String OriginalName, Boolean IsNameChange, Boolean IsActive, Boolean IsDeflated, String DeflatableClass, String DeflatedRoleNames, String UName, Integer DRUMPK, Boolean Ide) {
        this.Description = Description;
        this.GroupType = GroupType;
        this.GroupID = GroupID;
        this.GroupTypeID = GroupTypeID;
        this.Phone = Phone;
        this.Branch = Branch;
        this.EMail = EMail;
        this.SystemID = SystemID;
        this.DataProviderID = DataProviderID;
        this.LongName = LongName;
        this.Code = Code;
        this.Who = Who;
        this.DRUMID = DRUMID;
        this.EmailAddress = EmailAddress;
        this.CountryID = CountryID;
        this.Version = Version;
        this.Currency = Currency;
        this.DataProvider = DataProvider;
        this.IsIde = IsIde;
        this.DRUMRole = DRUMRole;
        this.Flag = Flag;
        this.CurrencyID = CurrencyID;
        this.Country = Country;
        this.When = When;
        this.DefaultAddress = DefaultAddress;
        this.Name = Name;
        this.DRUMStatusID = DRUMStatusID;
        this.DRUMStatus = DRUMStatus;
        this.DRUMRoleID = DRUMRoleID;
        this.UCode = UCode;
        this.OriginalName = OriginalName;
        this.IsNameChange = IsNameChange;
        this.IsActive = IsActive;
        this.IsDeflated = IsDeflated;
        this.DeflatableClass = DeflatableClass;
        this.DeflatedRoleNames = DeflatedRoleNames;
        this.UName = UName;
        this.DRUMPK = DRUMPK;
        this.Ide = Ide;
    }

    public String getBranch() {
        return this.Branch;
    }
    
    public void setBranch(String Branch) {
        this.Branch = Branch;
    }

    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    public CountryData getCountry() {
        return this.Country;
    }
    
    public void setCountry(CountryData Country) {
        this.Country = Country;
    }

    public Integer getCountryID() {
        return this.CountryID;
    }
    
    public void setCountryID(Integer CountryID) {
        this.CountryID = CountryID;
    }

    public CurrencyData getCurrency() {
        return this.Currency;
    }
    
    public void setCurrency(CurrencyData Currency) {
        this.Currency = Currency;
    }

    public Integer getCurrencyID() {
        return this.CurrencyID;
    }
    
    public void setCurrencyID(Integer CurrencyID) {
        this.CurrencyID = CurrencyID;
    }

    public Integer getDRUMID() {
        return this.DRUMID;
    }
    
    public void setDRUMID(Integer DRUMID) {
        this.DRUMID = DRUMID;
    }

    public Integer getDRUMPK() {
        return this.DRUMPK;
    }
    
    public void setDRUMPK(Integer DRUMPK) {
        this.DRUMPK = DRUMPK;
    }

    public GLTData getDRUMRole() {
        return this.DRUMRole;
    }
    
    public void setDRUMRole(GLTData DRUMRole) {
        this.DRUMRole = DRUMRole;
    }

    public Integer getDRUMRoleID() {
        return this.DRUMRoleID;
    }
    
    public void setDRUMRoleID(Integer DRUMRoleID) {
        this.DRUMRoleID = DRUMRoleID;
    }

    public GLTData getDRUMStatus() {
        return this.DRUMStatus;
    }
    
    public void setDRUMStatus(GLTData DRUMStatus) {
        this.DRUMStatus = DRUMStatus;
    }

    public Integer getDRUMStatusID() {
        return this.DRUMStatusID;
    }
    
    public void setDRUMStatusID(Integer DRUMStatusID) {
        this.DRUMStatusID = DRUMStatusID;
    }

    public DataProviderData getDataProvider() {
        return this.DataProvider;
    }
    
    public void setDataProvider(DataProviderData DataProvider) {
        this.DataProvider = DataProvider;
    }

    public Integer getDataProviderID() {
        return this.DataProviderID;
    }
    
    public void setDataProviderID(Integer DataProviderID) {
        this.DataProviderID = DataProviderID;
    }

    public AddressData getDefaultAddress() {
        return this.DefaultAddress;
    }
    
    public void setDefaultAddress(AddressData DefaultAddress) {
        this.DefaultAddress = DefaultAddress;
    }

    public String getDeflatableClass() {
        return this.DeflatableClass;
    }
    
    public void setDeflatableClass(String DeflatableClass) {
        this.DeflatableClass = DeflatableClass;
    }

    public String getDeflatedRoleNames() {
        return this.DeflatedRoleNames;
    }
    
    public void setDeflatedRoleNames(String DeflatedRoleNames) {
        this.DeflatedRoleNames = DeflatedRoleNames;
    }

    public String getDescription() {
        return this.Description;
    }
    
    public void setDescription(String Description) {
        this.Description = Description;
    }

    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }

    public AddressData getEmailAddress() {
        return this.EmailAddress;
    }
    
    public void setEmailAddress(AddressData EmailAddress) {
        this.EmailAddress = EmailAddress;
    }

    public Boolean getFlag() {
        return this.Flag;
    }
    
    public void setFlag(Boolean Flag) {
        this.Flag = Flag;
    }

    public Integer getGroupID() {
        return this.GroupID;
    }
    
    public void setGroupID(Integer GroupID) {
        this.GroupID = GroupID;
    }

    public GLTData getGroupType() {
        return this.GroupType;
    }
    
    public void setGroupType(GLTData GroupType) {
        this.GroupType = GroupType;
    }

    public Integer getGroupTypeID() {
        return this.GroupTypeID;
    }
    
    public void setGroupTypeID(Integer GroupTypeID) {
        this.GroupTypeID = GroupTypeID;
    }

    public Boolean getIde() {
        return this.Ide;
    }
    
    public void setIde(Boolean Ide) {
        this.Ide = Ide;
    }

    public Boolean getIsActive() {
        return this.IsActive;
    }
    
    public void setIsActive(Boolean IsActive) {
        this.IsActive = IsActive;
    }

    public Boolean getIsDeflated() {
        return this.IsDeflated;
    }
    
    public void setIsDeflated(Boolean IsDeflated) {
        this.IsDeflated = IsDeflated;
    }

    public Boolean getIsIde() {
        return this.IsIde;
    }
    
    public void setIsIde(Boolean IsIde) {
        this.IsIde = IsIde;
    }

    public Boolean getIsNameChange() {
        return this.IsNameChange;
    }
    
    public void setIsNameChange(Boolean IsNameChange) {
        this.IsNameChange = IsNameChange;
    }

    public String getLongName() {
        return this.LongName;
    }
    
    public void setLongName(String LongName) {
        this.LongName = LongName;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    public String getOriginalName() {
        return this.OriginalName;
    }
    
    public void setOriginalName(String OriginalName) {
        this.OriginalName = OriginalName;
    }

    public String getPhone() {
        return this.Phone;
    }
    
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    public Integer getSystemID() {
        return this.SystemID;
    }
    
    public void setSystemID(Integer SystemID) {
        this.SystemID = SystemID;
    }

    public String getUCode() {
        return this.UCode;
    }
    
    public void setUCode(String UCode) {
        this.UCode = UCode;
    }

    public String getUName() {
        return this.UName;
    }
    
    public void setUName(String UName) {
        this.UName = UName;
    }

    public Integer getVersion() {
        return this.Version;
    }
    
    public void setVersion(Integer Version) {
        this.Version = Version;
    }

    public String getWhen() {
        return this.When;
    }
    
    public void setWhen(String When) {
        this.When = When;
    }

    public String getWho() {
        return this.Who;
    }
    
    public void setWho(String Who) {
        this.Who = Who;
    }

}