package com.cip.transactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="IncomeStatus")
public class IncomeStatus implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private Integer StatusCode;
    @XmlElement
    private String StatusName;

    public IncomeStatus() {
    }
    
    public IncomeStatus(String StatusName, Integer StatusCode) {
        this.StatusName = StatusName;
        this.StatusCode = StatusCode;
    }
    
    public IncomeStatus(Integer StatusCode, String StatusName) {
        this.StatusCode = StatusCode;
        this.StatusName = StatusName;
    }

    public Integer getStatusCode() {
        return this.StatusCode;
    }
    
    public void setStatusCode(Integer StatusCode) {
        this.StatusCode = StatusCode;
    }

    public String getStatusName() {
        return this.StatusName;
    }
    
    public void setStatusName(String StatusName) {
        this.StatusName = StatusName;
    }

}