package com.cip.transactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="IndustryClassificationData")
public class IndustryClassificationData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private String ColourCode;
    @XmlElement
    private String Description;
    @XmlElement
    private String ExternalCode;
    @XmlElement
    private Integer GroupLevel;
    @XmlElement
    private Integer IndustryClassificationID;
    @XmlElement
    private String Name;
    @XmlElement
    private Integer Status;

    public IndustryClassificationData() {
    }
    
    public IndustryClassificationData(Integer Status, String Description, Integer GroupLevel, String ColourCode, String ExternalCode, Integer IndustryClassificationID, String Name) {
        this.Status = Status;
        this.Description = Description;
        this.GroupLevel = GroupLevel;
        this.ColourCode = ColourCode;
        this.ExternalCode = ExternalCode;
        this.IndustryClassificationID = IndustryClassificationID;
        this.Name = Name;
    }
    
    public IndustryClassificationData(String ColourCode, String Description, String ExternalCode, Integer GroupLevel, Integer IndustryClassificationID, String Name, Integer Status) {
        this.ColourCode = ColourCode;
        this.Description = Description;
        this.ExternalCode = ExternalCode;
        this.GroupLevel = GroupLevel;
        this.IndustryClassificationID = IndustryClassificationID;
        this.Name = Name;
        this.Status = Status;
    }

    public String getColourCode() {
        return this.ColourCode;
    }
    
    public void setColourCode(String ColourCode) {
        this.ColourCode = ColourCode;
    }

    public String getDescription() {
        return this.Description;
    }
    
    public void setDescription(String Description) {
        this.Description = Description;
    }

    public String getExternalCode() {
        return this.ExternalCode;
    }
    
    public void setExternalCode(String ExternalCode) {
        this.ExternalCode = ExternalCode;
    }

    public Integer getGroupLevel() {
        return this.GroupLevel;
    }
    
    public void setGroupLevel(Integer GroupLevel) {
        this.GroupLevel = GroupLevel;
    }

    public Integer getIndustryClassificationID() {
        return this.IndustryClassificationID;
    }
    
    public void setIndustryClassificationID(Integer IndustryClassificationID) {
        this.IndustryClassificationID = IndustryClassificationID;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    public Integer getStatus() {
        return this.Status;
    }
    
    public void setStatus(Integer Status) {
        this.Status = Status;
    }

}