package com.cip.transactions;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="IssueData")
public class IssueData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private String AILStatus;
    @XmlElement
    private String AssetCode;
    @XmlElement
    private AssetTypeData AssetType;
    @XmlElement
    private CountryData Country;
    @XmlElement
    private BigDecimal CouponRate;
    @XmlElement
    private CurrencyData Currency;
    @XmlElement
    private String DRP;
    @XmlElement
    private String Description;
    @XmlElement
    private BigDecimal ExercisePrice;
    @XmlElement
    private java.util.Date ExpiryDate;
    @XmlElement
    private Boolean HasMandate;
    @XmlElement
    private String ISIN;
    @XmlElement
    private String IncomeType;
    @XmlElement
    private IndustryClassificationData IndustryClassification;
    @XmlElement
    private String IndustryClassificationName;
    @XmlElement
    private Boolean IsBond;
    @XmlElement
    private Boolean IsTypeME;
    @XmlElement
    private java.util.Date IssueDate;
    @XmlElement
    private Integer IssueID;
    @XmlElement
    private IssuerData Issuer;
    @XmlElement
    private java.util.Date LastCouponDate;
    @XmlElement
    private GLTData ManagedType;
    @XmlElement
    private java.util.Date MaturityDate;
    @XmlElement
    private String Name;
    @XmlElement
    private java.util.Date NextCouponDate;
    @XmlElement
    private java.util.Date OddFirstCouponDate;
    @XmlElement
    private java.util.Date OddLastCouponDate;
    @XmlElement
    private String PIEStatus;
    @XmlElement
    private String Status;
    @XmlElement
    private BigDecimal TradableAmount;

    public IssueData() {
    }
    
    public IssueData(java.util.Date ExpiryDate, String DRP, String Description, IssuerData Issuer, java.util.Date LastCouponDate, BigDecimal ExercisePrice, String AssetCode, java.util.Date OddFirstCouponDate, String Name, Boolean HasMandate, String AILStatus, CurrencyData Currency, String IncomeType, BigDecimal CouponRate, String Status, GLTData ManagedType, String PIEStatus, String IndustryClassificationName, java.util.Date IssueDate, IndustryClassificationData IndustryClassification, Boolean IsBond, java.util.Date MaturityDate, java.util.Date NextCouponDate, Boolean IsTypeME, String ISIN, BigDecimal TradableAmount, AssetTypeData AssetType, CountryData Country, Integer IssueID, java.util.Date OddLastCouponDate) {
        this.ExpiryDate = ExpiryDate;
        this.DRP = DRP;
        this.Description = Description;
        this.Issuer = Issuer;
        this.LastCouponDate = LastCouponDate;
        this.ExercisePrice = ExercisePrice;
        this.AssetCode = AssetCode;
        this.OddFirstCouponDate = OddFirstCouponDate;
        this.Name = Name;
        this.HasMandate = HasMandate;
        this.AILStatus = AILStatus;
        this.Currency = Currency;
        this.IncomeType = IncomeType;
        this.CouponRate = CouponRate;
        this.Status = Status;
        this.ManagedType = ManagedType;
        this.PIEStatus = PIEStatus;
        this.IndustryClassificationName = IndustryClassificationName;
        this.IssueDate = IssueDate;
        this.IndustryClassification = IndustryClassification;
        this.IsBond = IsBond;
        this.MaturityDate = MaturityDate;
        this.NextCouponDate = NextCouponDate;
        this.IsTypeME = IsTypeME;
        this.ISIN = ISIN;
        this.TradableAmount = TradableAmount;
        this.AssetType = AssetType;
        this.Country = Country;
        this.IssueID = IssueID;
        this.OddLastCouponDate = OddLastCouponDate;
    }
    
    public IssueData(AssetTypeData AssetType, BigDecimal ExercisePrice, String IncomeType, String AssetCode, IssuerData Issuer, BigDecimal CouponRate, String DRP, CurrencyData Currency, String Description, String AILStatus, CountryData Country, Integer IssueID, String ISIN, String Name, String Status, String PIEStatus, Boolean IsBond, GLTData ManagedType, String IndustryClassificationName, IndustryClassificationData IndustryClassification, BigDecimal TradableAmount, java.util.Date IssueDate, java.util.Date MaturityDate, java.util.Date OddFirstCouponDate, java.util.Date OddLastCouponDate, java.util.Date ExpiryDate, java.util.Date NextCouponDate, java.util.Date LastCouponDate, Boolean HasMandate, Boolean IsTypeME) {
        this.AssetType = AssetType;
        this.ExercisePrice = ExercisePrice;
        this.IncomeType = IncomeType;
        this.AssetCode = AssetCode;
        this.Issuer = Issuer;
        this.CouponRate = CouponRate;
        this.DRP = DRP;
        this.Currency = Currency;
        this.Description = Description;
        this.AILStatus = AILStatus;
        this.Country = Country;
        this.IssueID = IssueID;
        this.ISIN = ISIN;
        this.Name = Name;
        this.Status = Status;
        this.PIEStatus = PIEStatus;
        this.IsBond = IsBond;
        this.ManagedType = ManagedType;
        this.IndustryClassificationName = IndustryClassificationName;
        this.IndustryClassification = IndustryClassification;
        this.TradableAmount = TradableAmount;
        this.IssueDate = IssueDate;
        this.MaturityDate = MaturityDate;
        this.OddFirstCouponDate = OddFirstCouponDate;
        this.OddLastCouponDate = OddLastCouponDate;
        this.ExpiryDate = ExpiryDate;
        this.NextCouponDate = NextCouponDate;
        this.LastCouponDate = LastCouponDate;
        this.HasMandate = HasMandate;
        this.IsTypeME = IsTypeME;
    }

    public String getAILStatus() {
        return this.AILStatus;
    }
    
    public void setAILStatus(String AILStatus) {
        this.AILStatus = AILStatus;
    }

    public String getAssetCode() {
        return this.AssetCode;
    }
    
    public void setAssetCode(String AssetCode) {
        this.AssetCode = AssetCode;
    }

    public AssetTypeData getAssetType() {
        return this.AssetType;
    }
    
    public void setAssetType(AssetTypeData AssetType) {
        this.AssetType = AssetType;
    }

    public CountryData getCountry() {
        return this.Country;
    }
    
    public void setCountry(CountryData Country) {
        this.Country = Country;
    }

    public BigDecimal getCouponRate() {
        return this.CouponRate;
    }
    
    public void setCouponRate(BigDecimal CouponRate) {
        this.CouponRate = CouponRate;
    }

    public CurrencyData getCurrency() {
        return this.Currency;
    }
    
    public void setCurrency(CurrencyData Currency) {
        this.Currency = Currency;
    }

    public String getDRP() {
        return this.DRP;
    }
    
    public void setDRP(String DRP) {
        this.DRP = DRP;
    }

    public String getDescription() {
        return this.Description;
    }
    
    public void setDescription(String Description) {
        this.Description = Description;
    }

    public BigDecimal getExercisePrice() {
        return this.ExercisePrice;
    }
    
    public void setExercisePrice(BigDecimal ExercisePrice) {
        this.ExercisePrice = ExercisePrice;
    }

    public java.util.Date getExpiryDate() {
        return this.ExpiryDate;
    }
    
    public void setExpiryDate(java.util.Date ExpiryDate) {
        this.ExpiryDate = ExpiryDate;
    }

    public Boolean getHasMandate() {
        return this.HasMandate;
    }
    
    public void setHasMandate(Boolean HasMandate) {
        this.HasMandate = HasMandate;
    }

    public String getISIN() {
        return this.ISIN;
    }
    
    public void setISIN(String ISIN) {
        this.ISIN = ISIN;
    }

    public String getIncomeType() {
        return this.IncomeType;
    }
    
    public void setIncomeType(String IncomeType) {
        this.IncomeType = IncomeType;
    }

    public IndustryClassificationData getIndustryClassification() {
        return this.IndustryClassification;
    }
    
    public void setIndustryClassification(IndustryClassificationData IndustryClassification) {
        this.IndustryClassification = IndustryClassification;
    }

    public String getIndustryClassificationName() {
        return this.IndustryClassificationName;
    }
    
    public void setIndustryClassificationName(String IndustryClassificationName) {
        this.IndustryClassificationName = IndustryClassificationName;
    }

    public Boolean getIsBond() {
        return this.IsBond;
    }
    
    public void setIsBond(Boolean IsBond) {
        this.IsBond = IsBond;
    }

    public Boolean getIsTypeME() {
        return this.IsTypeME;
    }
    
    public void setIsTypeME(Boolean IsTypeME) {
        this.IsTypeME = IsTypeME;
    }

    public java.util.Date getIssueDate() {
        return this.IssueDate;
    }
    
    public void setIssueDate(java.util.Date IssueDate) {
        this.IssueDate = IssueDate;
    }

    public Integer getIssueID() {
        return this.IssueID;
    }
    
    public void setIssueID(Integer IssueID) {
        this.IssueID = IssueID;
    }

    public IssuerData getIssuer() {
        return this.Issuer;
    }
    
    public void setIssuer(IssuerData Issuer) {
        this.Issuer = Issuer;
    }

    public java.util.Date getLastCouponDate() {
        return this.LastCouponDate;
    }
    
    public void setLastCouponDate(java.util.Date LastCouponDate) {
        this.LastCouponDate = LastCouponDate;
    }

    public GLTData getManagedType() {
        return this.ManagedType;
    }
    
    public void setManagedType(GLTData ManagedType) {
        this.ManagedType = ManagedType;
    }

    public java.util.Date getMaturityDate() {
        return this.MaturityDate;
    }
    
    public void setMaturityDate(java.util.Date MaturityDate) {
        this.MaturityDate = MaturityDate;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    public java.util.Date getNextCouponDate() {
        return this.NextCouponDate;
    }
    
    public void setNextCouponDate(java.util.Date NextCouponDate) {
        this.NextCouponDate = NextCouponDate;
    }

    public java.util.Date getOddFirstCouponDate() {
        return this.OddFirstCouponDate;
    }
    
    public void setOddFirstCouponDate(java.util.Date OddFirstCouponDate) {
        this.OddFirstCouponDate = OddFirstCouponDate;
    }

    public java.util.Date getOddLastCouponDate() {
        return this.OddLastCouponDate;
    }
    
    public void setOddLastCouponDate(java.util.Date OddLastCouponDate) {
        this.OddLastCouponDate = OddLastCouponDate;
    }

    public String getPIEStatus() {
        return this.PIEStatus;
    }
    
    public void setPIEStatus(String PIEStatus) {
        this.PIEStatus = PIEStatus;
    }

    public String getStatus() {
        return this.Status;
    }
    
    public void setStatus(String Status) {
        this.Status = Status;
    }

    public BigDecimal getTradableAmount() {
        return this.TradableAmount;
    }
    
    public void setTradableAmount(BigDecimal TradableAmount) {
        this.TradableAmount = TradableAmount;
    }

}