package com.cip.transactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="IssuerData")
public class IssuerData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private Integer AuditID;
    @XmlElement
    private String Branch;
    @XmlElement
    private String Code;
    @XmlElement
    private CountryData Country;
    @XmlElement
    private Integer CountryID;
    @XmlElement
    private CurrencyData Currency;
    @XmlElement
    private Integer CurrencyID;
    @XmlElement
    private Integer DRUMID;
    @XmlElement
    private Integer DRUMPK;
    @XmlElement
    private GLTData DRUMRole;
    @XmlElement
    private Integer DRUMRoleID;
    @XmlElement
    private GLTData DRUMStatus;
    @XmlElement
    private Integer DRUMStatusID;
    @XmlElement
    private DataProviderData DataProvider;
    @XmlElement
    private Integer DataProviderID;
    @XmlElement
    private AddressData DefaultAddress;
    @XmlElement
    private String DeflatableClass;
    @XmlElement
    private String DeflatedRoleNames;
    @XmlElement
    private String EMail;
    @XmlElement
    private AddressData EmailAddress;

    @XmlElement
    private Integer FinancialYearEndFreq;
    @XmlElement
    private Boolean Flag;
    @XmlElement
    private Boolean Ide;
    @XmlElement
    private Boolean IsActive;
    @XmlElement
    private Boolean IsCustodian;
    @XmlElement
    private Boolean IsDeflated;
    @XmlElement
    private Boolean IsIde;
    @XmlElement
    private Boolean IsIssuer;
    @XmlElement
    private Boolean IsNameChange;
    @XmlElement
    private Boolean IsRegistrar;
    @XmlElement
    private Integer IssuerID;
    @XmlElement
    private String LogoURL;
    @XmlElement
    private String LongName;
    @XmlElement
    private String Name;
    @XmlElement
    private Integer OrganisationID;
    @XmlElement
    private GLTData OrganisationType;
    @XmlElement
    private Integer OrganisationTypeID;
    @XmlElement
    private String OriginalName;
    @XmlElement
    private String OutlookText;
    @XmlElement
    private String OverviewText;
    @XmlElement
    private Integer PaymentOffsetDays;
    @XmlElement
    private String Phone;
    @XmlElement
    private Integer SystemID;
    @XmlElement
    private String UCode;
    @XmlElement
    private String UName;
    @XmlElement
    private Integer Version;
    @XmlElement
    private String WebSite;
    @XmlElement
    private String When;
    @XmlElement
    private String Who;

    public IssuerData() {
    }
    
    public IssuerData(Integer CountryID, String DeflatedRoleNames, Boolean IsDeflated, Integer PaymentOffsetDays, String LogoURL, Integer SystemID, Boolean Ide, Integer DRUMStatusID, String Name, String OverviewText, Boolean IsRegistrar, Integer Version, Integer DRUMPK, CurrencyData Currency, Integer FinancialYearEndFreq, GLTData DRUMStatus, Boolean IsIssuer, String Who, Boolean IsNameChange, String OriginalName, String Code, Boolean Flag, AddressData EmailAddress, String UCode, Integer IssuerID, String DeflatableClass, String WebSite, CountryData Country, Boolean IsIde, AddressData DefaultAddress, GLTData DRUMRole, Boolean IsActive, Integer OrganisationID, DataProviderData DataProvider, String UName, String Phone, String Branch, Integer AuditID, GLTData OrganisationType, String EMail, Integer CurrencyID, String When, String OutlookText, Boolean IsCustodian, String LongName, Integer DRUMID, Integer OrganisationTypeID, Integer DataProviderID, Integer DRUMRoleID) {
        this.CountryID = CountryID;
        this.DeflatedRoleNames = DeflatedRoleNames;
        this.IsDeflated = IsDeflated;
        this.PaymentOffsetDays = PaymentOffsetDays;
        this.LogoURL = LogoURL;
        this.SystemID = SystemID;
        this.Ide = Ide;
        this.DRUMStatusID = DRUMStatusID;
        this.Name = Name;
        this.OverviewText = OverviewText;
        this.IsRegistrar = IsRegistrar;
        this.Version = Version;
        this.DRUMPK = DRUMPK;
        this.Currency = Currency;
        this.FinancialYearEndFreq = FinancialYearEndFreq;
        this.DRUMStatus = DRUMStatus;
        this.IsIssuer = IsIssuer;
        this.Who = Who;
        this.IsNameChange = IsNameChange;
        this.OriginalName = OriginalName;
        this.Code = Code;
        this.Flag = Flag;
        this.EmailAddress = EmailAddress;
        this.UCode = UCode;
        this.IssuerID = IssuerID;
        this.DeflatableClass = DeflatableClass;
        this.WebSite = WebSite;
        this.Country = Country;
        this.IsIde = IsIde;
        this.DefaultAddress = DefaultAddress;
        this.DRUMRole = DRUMRole;
        this.IsActive = IsActive;
        this.OrganisationID = OrganisationID;
        this.DataProvider = DataProvider;
        this.UName = UName;
        this.Phone = Phone;
        this.Branch = Branch;
        this.AuditID = AuditID;
        this.OrganisationType = OrganisationType;
        this.EMail = EMail;
        this.CurrencyID = CurrencyID;
        this.When = When;
        this.OutlookText = OutlookText;
        this.IsCustodian = IsCustodian;
        this.LongName = LongName;
        this.DRUMID = DRUMID;
        this.OrganisationTypeID = OrganisationTypeID;
        this.DataProviderID = DataProviderID;
        this.DRUMRoleID = DRUMRoleID;
    }
    
    public IssuerData(Integer IssuerID, Integer OrganisationTypeID, GLTData OrganisationType, Integer OrganisationID, Boolean IsCustodian, Boolean IsRegistrar, Boolean IsIssuer, String Phone, String Branch, String EMail, Integer SystemID, Integer DataProviderID, String LongName, String Code, String Who, Integer DRUMID, AddressData EmailAddress, Integer CountryID, Integer Version, CurrencyData Currency, DataProviderData DataProvider, Boolean IsIde, GLTData DRUMRole, Boolean Flag, Integer CurrencyID, CountryData Country, String When, AddressData DefaultAddress, String Name, Integer DRUMStatusID, GLTData DRUMStatus, Integer DRUMRoleID, String UCode, String OriginalName, Boolean IsNameChange, Boolean IsActive, Boolean IsDeflated, String DeflatableClass, String DeflatedRoleNames, String UName, Integer DRUMPK, String WebSite, String OutlookText, String OverviewText, String LogoURL, Boolean Ide, Integer FinancialYearEndFreq, Integer AuditID, Integer PaymentOffsetDays) {
        this.IssuerID = IssuerID;
        this.OrganisationTypeID = OrganisationTypeID;
        this.OrganisationType = OrganisationType;
        this.OrganisationID = OrganisationID;
        this.IsCustodian = IsCustodian;
        this.IsRegistrar = IsRegistrar;
        this.IsIssuer = IsIssuer;
        this.Phone = Phone;
        this.Branch = Branch;
        this.EMail = EMail;
        this.SystemID = SystemID;
        this.DataProviderID = DataProviderID;
        this.LongName = LongName;
        this.Code = Code;
        this.Who = Who;
        this.DRUMID = DRUMID;
        this.EmailAddress = EmailAddress;
        this.CountryID = CountryID;
        this.Version = Version;
        this.Currency = Currency;
        this.DataProvider = DataProvider;
        this.IsIde = IsIde;
        this.DRUMRole = DRUMRole;
        this.Flag = Flag;
        this.CurrencyID = CurrencyID;
        this.Country = Country;
        this.When = When;
        this.DefaultAddress = DefaultAddress;
        this.Name = Name;
        this.DRUMStatusID = DRUMStatusID;
        this.DRUMStatus = DRUMStatus;
        this.DRUMRoleID = DRUMRoleID;
        this.UCode = UCode;
        this.OriginalName = OriginalName;
        this.IsNameChange = IsNameChange;
        this.IsActive = IsActive;
        this.IsDeflated = IsDeflated;
        this.DeflatableClass = DeflatableClass;
        this.DeflatedRoleNames = DeflatedRoleNames;
        this.UName = UName;
        this.DRUMPK = DRUMPK;
        this.WebSite = WebSite;
        this.OutlookText = OutlookText;
        this.OverviewText = OverviewText;
        this.LogoURL = LogoURL;
        this.Ide = Ide;
        this.FinancialYearEndFreq = FinancialYearEndFreq;
        this.AuditID = AuditID;
        this.PaymentOffsetDays = PaymentOffsetDays;
    }

    public Integer getAuditID() {
        return this.AuditID;
    }
    
    public void setAuditID(Integer AuditID) {
        this.AuditID = AuditID;
    }

    public String getBranch() {
        return this.Branch;
    }
    
    public void setBranch(String Branch) {
        this.Branch = Branch;
    }

    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    public CountryData getCountry() {
        return this.Country;
    }
    
    public void setCountry(CountryData Country) {
        this.Country = Country;
    }

    public Integer getCountryID() {
        return this.CountryID;
    }
    
    public void setCountryID(Integer CountryID) {
        this.CountryID = CountryID;
    }

    public CurrencyData getCurrency() {
        return this.Currency;
    }
    
    public void setCurrency(CurrencyData Currency) {
        this.Currency = Currency;
    }

    public Integer getCurrencyID() {
        return this.CurrencyID;
    }
    
    public void setCurrencyID(Integer CurrencyID) {
        this.CurrencyID = CurrencyID;
    }

    public Integer getDRUMID() {
        return this.DRUMID;
    }
    
    public void setDRUMID(Integer DRUMID) {
        this.DRUMID = DRUMID;
    }

    public Integer getDRUMPK() {
        return this.DRUMPK;
    }
    
    public void setDRUMPK(Integer DRUMPK) {
        this.DRUMPK = DRUMPK;
    }

    public GLTData getDRUMRole() {
        return this.DRUMRole;
    }
    
    public void setDRUMRole(GLTData DRUMRole) {
        this.DRUMRole = DRUMRole;
    }

    public Integer getDRUMRoleID() {
        return this.DRUMRoleID;
    }
    
    public void setDRUMRoleID(Integer DRUMRoleID) {
        this.DRUMRoleID = DRUMRoleID;
    }

    public GLTData getDRUMStatus() {
        return this.DRUMStatus;
    }
    
    public void setDRUMStatus(GLTData DRUMStatus) {
        this.DRUMStatus = DRUMStatus;
    }

    public Integer getDRUMStatusID() {
        return this.DRUMStatusID;
    }
    
    public void setDRUMStatusID(Integer DRUMStatusID) {
        this.DRUMStatusID = DRUMStatusID;
    }

    public DataProviderData getDataProvider() {
        return this.DataProvider;
    }
    
    public void setDataProvider(DataProviderData DataProvider) {
        this.DataProvider = DataProvider;
    }

    public Integer getDataProviderID() {
        return this.DataProviderID;
    }
    
    public void setDataProviderID(Integer DataProviderID) {
        this.DataProviderID = DataProviderID;
    }

    public AddressData getDefaultAddress() {
        return this.DefaultAddress;
    }
    
    public void setDefaultAddress(AddressData DefaultAddress) {
        this.DefaultAddress = DefaultAddress;
    }

    public String getDeflatableClass() {
        return this.DeflatableClass;
    }
    
    public void setDeflatableClass(String DeflatableClass) {
        this.DeflatableClass = DeflatableClass;
    }

    public String getDeflatedRoleNames() {
        return this.DeflatedRoleNames;
    }
    
    public void setDeflatedRoleNames(String DeflatedRoleNames) {
        this.DeflatedRoleNames = DeflatedRoleNames;
    }

    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }

    public AddressData getEmailAddress() {
        return this.EmailAddress;
    }
    
    public void setEmailAddress(AddressData EmailAddress) {
        this.EmailAddress = EmailAddress;
    }


    public Integer getFinancialYearEndFreq() {
        return this.FinancialYearEndFreq;
    }
    
    public void setFinancialYearEndFreq(Integer FinancialYearEndFreq) {
        this.FinancialYearEndFreq = FinancialYearEndFreq;
    }

    public Boolean getFlag() {
        return this.Flag;
    }
    
    public void setFlag(Boolean Flag) {
        this.Flag = Flag;
    }

    public Boolean getIde() {
        return this.Ide;
    }
    
    public void setIde(Boolean Ide) {
        this.Ide = Ide;
    }

    public Boolean getIsActive() {
        return this.IsActive;
    }
    
    public void setIsActive(Boolean IsActive) {
        this.IsActive = IsActive;
    }

    public Boolean getIsCustodian() {
        return this.IsCustodian;
    }
    
    public void setIsCustodian(Boolean IsCustodian) {
        this.IsCustodian = IsCustodian;
    }

    public Boolean getIsDeflated() {
        return this.IsDeflated;
    }
    
    public void setIsDeflated(Boolean IsDeflated) {
        this.IsDeflated = IsDeflated;
    }

    public Boolean getIsIde() {
        return this.IsIde;
    }
    
    public void setIsIde(Boolean IsIde) {
        this.IsIde = IsIde;
    }

    public Boolean getIsIssuer() {
        return this.IsIssuer;
    }
    
    public void setIsIssuer(Boolean IsIssuer) {
        this.IsIssuer = IsIssuer;
    }

    public Boolean getIsNameChange() {
        return this.IsNameChange;
    }
    
    public void setIsNameChange(Boolean IsNameChange) {
        this.IsNameChange = IsNameChange;
    }

    public Boolean getIsRegistrar() {
        return this.IsRegistrar;
    }
    
    public void setIsRegistrar(Boolean IsRegistrar) {
        this.IsRegistrar = IsRegistrar;
    }

    public Integer getIssuerID() {
        return this.IssuerID;
    }
    
    public void setIssuerID(Integer IssuerID) {
        this.IssuerID = IssuerID;
    }

    public String getLogoURL() {
        return this.LogoURL;
    }
    
    public void setLogoURL(String LogoURL) {
        this.LogoURL = LogoURL;
    }

    public String getLongName() {
        return this.LongName;
    }
    
    public void setLongName(String LongName) {
        this.LongName = LongName;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    public Integer getOrganisationID() {
        return this.OrganisationID;
    }
    
    public void setOrganisationID(Integer OrganisationID) {
        this.OrganisationID = OrganisationID;
    }

    public GLTData getOrganisationType() {
        return this.OrganisationType;
    }
    
    public void setOrganisationType(GLTData OrganisationType) {
        this.OrganisationType = OrganisationType;
    }

    public Integer getOrganisationTypeID() {
        return this.OrganisationTypeID;
    }
    
    public void setOrganisationTypeID(Integer OrganisationTypeID) {
        this.OrganisationTypeID = OrganisationTypeID;
    }

    public String getOriginalName() {
        return this.OriginalName;
    }
    
    public void setOriginalName(String OriginalName) {
        this.OriginalName = OriginalName;
    }

    public String getOutlookText() {
        return this.OutlookText;
    }
    
    public void setOutlookText(String OutlookText) {
        this.OutlookText = OutlookText;
    }

    public String getOverviewText() {
        return this.OverviewText;
    }
    
    public void setOverviewText(String OverviewText) {
        this.OverviewText = OverviewText;
    }

    public Integer getPaymentOffsetDays() {
        return this.PaymentOffsetDays;
    }
    
    public void setPaymentOffsetDays(Integer PaymentOffsetDays) {
        this.PaymentOffsetDays = PaymentOffsetDays;
    }

    public String getPhone() {
        return this.Phone;
    }
    
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    public Integer getSystemID() {
        return this.SystemID;
    }
    
    public void setSystemID(Integer SystemID) {
        this.SystemID = SystemID;
    }

    public String getUCode() {
        return this.UCode;
    }
    
    public void setUCode(String UCode) {
        this.UCode = UCode;
    }

    public String getUName() {
        return this.UName;
    }
    
    public void setUName(String UName) {
        this.UName = UName;
    }

    public Integer getVersion() {
        return this.Version;
    }
    
    public void setVersion(Integer Version) {
        this.Version = Version;
    }

    public String getWebSite() {
        return this.WebSite;
    }
    
    public void setWebSite(String WebSite) {
        this.WebSite = WebSite;
    }

    public String getWhen() {
        return this.When;
    }
    
    public void setWhen(String When) {
        this.When = When;
    }

    public String getWho() {
        return this.Who;
    }
    
    public void setWho(String Who) {
        this.Who = Who;
    }

}