package com.cip.transactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="PersonData")
public class PersonData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private String Branch;
    @XmlElement
    private String Code;
    @XmlElement
    private CountryData Country;
    @XmlElement
    private Integer CountryID;
    @XmlElement
    private CurrencyData Currency;
    @XmlElement
    private Integer CurrencyID;
    @XmlElement
    private Integer DRUMID;
    @XmlElement
    private Integer DRUMPK;
    @XmlElement
    private GLTData DRUMRole;
    @XmlElement
    private Integer DRUMRoleID;
    @XmlElement
    private GLTData DRUMStatus;
    @XmlElement
    private Integer DRUMStatusID;
    @XmlElement
    private DataProviderData DataProvider;
    @XmlElement
    private Integer DataProviderID;
    @XmlElement
    private AddressData DefaultAddress;
    @XmlElement
    private String DeflatableClass;
    @XmlElement
    private String DeflatedRoleNames;
    @XmlElement
    private String EMail;
    @XmlElement
    private AddressData EmailAddress;
    @XmlElement
    private String FamilyNames;
    @XmlElement
    private Boolean Flag;
    @XmlElement
    private String FullName;
    @XmlElement
    private String GivenNames;
    @XmlElement
    private Boolean IsActive;
    @XmlElement
    private Boolean IsDeflated;
    @XmlElement
    private Boolean IsIde;
    @XmlElement
    private Boolean IsNameChange;
    @XmlElement
    private String LongName;
    @XmlElement
    private String Name;
    @XmlElement
    private String OriginalName;
    @XmlElement
    private Integer PersonID;
    @XmlElement
    private String Phone;
    @XmlElement
    private String Salutation;
    @XmlElement
    private String SurnameFirstname;
    @XmlElement
    private Integer SystemID;
    @XmlElement
    private String UCode;
    @XmlElement
    private String UName;
    @XmlElement
    private Integer Version;
    @XmlElement
    private String When;
    @XmlElement
    private String Who;

    public PersonData() {
    }
    
    public PersonData(Integer CountryID, String DeflatedRoleNames, AddressData DefaultAddress, Boolean IsDeflated, GLTData DRUMRole, Boolean IsActive, Integer SystemID, String FamilyNames, String Salutation, Integer DRUMStatusID, String Name, DataProviderData DataProvider, String UName, Integer PersonID, Integer Version, Integer DRUMPK, String GivenNames, String Phone, String Branch, CurrencyData Currency, GLTData DRUMStatus, String Who, Boolean IsNameChange, String OriginalName, String EMail, String Code, Boolean Flag, AddressData EmailAddress, Integer CurrencyID, String UCode, String When, String LongName, Integer DRUMID, String FullName, Integer DataProviderID, String SurnameFirstname, String DeflatableClass, CountryData Country, Boolean IsIde, Integer DRUMRoleID) {
        this.CountryID = CountryID;
        this.DeflatedRoleNames = DeflatedRoleNames;
        this.DefaultAddress = DefaultAddress;
        this.IsDeflated = IsDeflated;
        this.DRUMRole = DRUMRole;
        this.IsActive = IsActive;
        this.SystemID = SystemID;
        this.FamilyNames = FamilyNames;
        this.Salutation = Salutation;
        this.DRUMStatusID = DRUMStatusID;
        this.Name = Name;
        this.DataProvider = DataProvider;
        this.UName = UName;
        this.PersonID = PersonID;
        this.Version = Version;
        this.DRUMPK = DRUMPK;
        this.GivenNames = GivenNames;
        this.Phone = Phone;
        this.Branch = Branch;
        this.Currency = Currency;
        this.DRUMStatus = DRUMStatus;
        this.Who = Who;
        this.IsNameChange = IsNameChange;
        this.OriginalName = OriginalName;
        this.EMail = EMail;
        this.Code = Code;
        this.Flag = Flag;
        this.EmailAddress = EmailAddress;
        this.CurrencyID = CurrencyID;
        this.UCode = UCode;
        this.When = When;
        this.LongName = LongName;
        this.DRUMID = DRUMID;
        this.FullName = FullName;
        this.DataProviderID = DataProviderID;
        this.SurnameFirstname = SurnameFirstname;
        this.DeflatableClass = DeflatableClass;
        this.Country = Country;
        this.IsIde = IsIde;
        this.DRUMRoleID = DRUMRoleID;
    }
    
    public PersonData(String GivenNames, String FullName, Integer PersonID, String FamilyNames, String Salutation, String SurnameFirstname, String Phone, String Branch, String EMail, Integer SystemID, Integer DataProviderID, String LongName, String Code, String Who, Integer DRUMID, AddressData EmailAddress, Integer CountryID, Integer Version, CurrencyData Currency, DataProviderData DataProvider, Boolean IsIde, GLTData DRUMRole, Boolean Flag, Integer CurrencyID, CountryData Country, String When, AddressData DefaultAddress, String Name, Integer DRUMStatusID, GLTData DRUMStatus, Integer DRUMRoleID, String UCode, String OriginalName, Boolean IsNameChange, Boolean IsActive, Boolean IsDeflated, String DeflatableClass, String DeflatedRoleNames, String UName, Integer DRUMPK) {
        this.GivenNames = GivenNames;
        this.FullName = FullName;
        this.PersonID = PersonID;
        this.FamilyNames = FamilyNames;
        this.Salutation = Salutation;
        this.SurnameFirstname = SurnameFirstname;
        this.Phone = Phone;
        this.Branch = Branch;
        this.EMail = EMail;
        this.SystemID = SystemID;
        this.DataProviderID = DataProviderID;
        this.LongName = LongName;
        this.Code = Code;
        this.Who = Who;
        this.DRUMID = DRUMID;
        this.EmailAddress = EmailAddress;
        this.CountryID = CountryID;
        this.Version = Version;
        this.Currency = Currency;
        this.DataProvider = DataProvider;
        this.IsIde = IsIde;
        this.DRUMRole = DRUMRole;
        this.Flag = Flag;
        this.CurrencyID = CurrencyID;
        this.Country = Country;
        this.When = When;
        this.DefaultAddress = DefaultAddress;
        this.Name = Name;
        this.DRUMStatusID = DRUMStatusID;
        this.DRUMStatus = DRUMStatus;
        this.DRUMRoleID = DRUMRoleID;
        this.UCode = UCode;
        this.OriginalName = OriginalName;
        this.IsNameChange = IsNameChange;
        this.IsActive = IsActive;
        this.IsDeflated = IsDeflated;
        this.DeflatableClass = DeflatableClass;
        this.DeflatedRoleNames = DeflatedRoleNames;
        this.UName = UName;
        this.DRUMPK = DRUMPK;
    }

    public String getBranch() {
        return this.Branch;
    }
    
    public void setBranch(String Branch) {
        this.Branch = Branch;
    }

    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    public CountryData getCountry() {
        return this.Country;
    }
    
    public void setCountry(CountryData Country) {
        this.Country = Country;
    }

    public Integer getCountryID() {
        return this.CountryID;
    }
    
    public void setCountryID(Integer CountryID) {
        this.CountryID = CountryID;
    }

    public CurrencyData getCurrency() {
        return this.Currency;
    }
    
    public void setCurrency(CurrencyData Currency) {
        this.Currency = Currency;
    }

    public Integer getCurrencyID() {
        return this.CurrencyID;
    }
    
    public void setCurrencyID(Integer CurrencyID) {
        this.CurrencyID = CurrencyID;
    }

    public Integer getDRUMID() {
        return this.DRUMID;
    }
    
    public void setDRUMID(Integer DRUMID) {
        this.DRUMID = DRUMID;
    }

    public Integer getDRUMPK() {
        return this.DRUMPK;
    }
    
    public void setDRUMPK(Integer DRUMPK) {
        this.DRUMPK = DRUMPK;
    }

    public GLTData getDRUMRole() {
        return this.DRUMRole;
    }
    
    public void setDRUMRole(GLTData DRUMRole) {
        this.DRUMRole = DRUMRole;
    }

    public Integer getDRUMRoleID() {
        return this.DRUMRoleID;
    }
    
    public void setDRUMRoleID(Integer DRUMRoleID) {
        this.DRUMRoleID = DRUMRoleID;
    }

    public GLTData getDRUMStatus() {
        return this.DRUMStatus;
    }
    
    public void setDRUMStatus(GLTData DRUMStatus) {
        this.DRUMStatus = DRUMStatus;
    }

    public Integer getDRUMStatusID() {
        return this.DRUMStatusID;
    }
    
    public void setDRUMStatusID(Integer DRUMStatusID) {
        this.DRUMStatusID = DRUMStatusID;
    }

    public DataProviderData getDataProvider() {
        return this.DataProvider;
    }
    
    public void setDataProvider(DataProviderData DataProvider) {
        this.DataProvider = DataProvider;
    }

    public Integer getDataProviderID() {
        return this.DataProviderID;
    }
    
    public void setDataProviderID(Integer DataProviderID) {
        this.DataProviderID = DataProviderID;
    }

    public AddressData getDefaultAddress() {
        return this.DefaultAddress;
    }
    
    public void setDefaultAddress(AddressData DefaultAddress) {
        this.DefaultAddress = DefaultAddress;
    }

    public String getDeflatableClass() {
        return this.DeflatableClass;
    }
    
    public void setDeflatableClass(String DeflatableClass) {
        this.DeflatableClass = DeflatableClass;
    }

    public String getDeflatedRoleNames() {
        return this.DeflatedRoleNames;
    }
    
    public void setDeflatedRoleNames(String DeflatedRoleNames) {
        this.DeflatedRoleNames = DeflatedRoleNames;
    }

    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }

    public AddressData getEmailAddress() {
        return this.EmailAddress;
    }
    
    public void setEmailAddress(AddressData EmailAddress) {
        this.EmailAddress = EmailAddress;
    }

    public String getFamilyNames() {
        return this.FamilyNames;
    }
    
    public void setFamilyNames(String FamilyNames) {
        this.FamilyNames = FamilyNames;
    }

    public Boolean getFlag() {
        return this.Flag;
    }
    
    public void setFlag(Boolean Flag) {
        this.Flag = Flag;
    }

    public String getFullName() {
        return this.FullName;
    }
    
    public void setFullName(String FullName) {
        this.FullName = FullName;
    }

    public String getGivenNames() {
        return this.GivenNames;
    }
    
    public void setGivenNames(String GivenNames) {
        this.GivenNames = GivenNames;
    }

    public Boolean getIsActive() {
        return this.IsActive;
    }
    
    public void setIsActive(Boolean IsActive) {
        this.IsActive = IsActive;
    }

    public Boolean getIsDeflated() {
        return this.IsDeflated;
    }
    
    public void setIsDeflated(Boolean IsDeflated) {
        this.IsDeflated = IsDeflated;
    }

    public Boolean getIsIde() {
        return this.IsIde;
    }
    
    public void setIsIde(Boolean IsIde) {
        this.IsIde = IsIde;
    }

    public Boolean getIsNameChange() {
        return this.IsNameChange;
    }
    
    public void setIsNameChange(Boolean IsNameChange) {
        this.IsNameChange = IsNameChange;
    }

    public String getLongName() {
        return this.LongName;
    }
    
    public void setLongName(String LongName) {
        this.LongName = LongName;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    public String getOriginalName() {
        return this.OriginalName;
    }
    
    public void setOriginalName(String OriginalName) {
        this.OriginalName = OriginalName;
    }

    public Integer getPersonID() {
        return this.PersonID;
    }
    
    public void setPersonID(Integer PersonID) {
        this.PersonID = PersonID;
    }

    public String getPhone() {
        return this.Phone;
    }
    
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    public String getSalutation() {
        return this.Salutation;
    }
    
    public void setSalutation(String Salutation) {
        this.Salutation = Salutation;
    }

    public String getSurnameFirstname() {
        return this.SurnameFirstname;
    }
    
    public void setSurnameFirstname(String SurnameFirstname) {
        this.SurnameFirstname = SurnameFirstname;
    }

    public Integer getSystemID() {
        return this.SystemID;
    }
    
    public void setSystemID(Integer SystemID) {
        this.SystemID = SystemID;
    }

    public String getUCode() {
        return this.UCode;
    }
    
    public void setUCode(String UCode) {
        this.UCode = UCode;
    }

    public String getUName() {
        return this.UName;
    }
    
    public void setUName(String UName) {
        this.UName = UName;
    }

    public Integer getVersion() {
        return this.Version;
    }
    
    public void setVersion(Integer Version) {
        this.Version = Version;
    }

    public String getWhen() {
        return this.When;
    }
    
    public void setWhen(String When) {
        this.When = When;
    }

    public String getWho() {
        return this.Who;
    }
    
    public void setWho(String Who) {
        this.Who = Who;
    }

}