package com.cip.transactions;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="PortfolioData")
public class PortfolioData implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private GLTData AccountType;
    @XmlElement
    private CountryData Address3;
    @XmlElement
    private AdvisorData Advisor;
    @XmlElement
    private String BranchCode;
    @XmlElement
    private GLTData Brand;
    @XmlElement
    private Integer CBalID;
    @XmlElement
    private BigDecimal CashValue;
    @XmlElement
    private String Code;
    @XmlElement
    private CountryData Country;
    @XmlElement
    private CurrencyData Currency;
    @XmlElement
    private BigDecimal CurrentRate;
    @XmlElement
    private OrganisationData Custodian;
    @XmlElement
    private String DRPStatus;
    @XmlElement
    private Integer Default;
    @XmlElement
    private String DefaultAddress;
    @XmlElement
    private IncomeStatus DividendStatus;
    @XmlElement
    private String DividendStatusName;
    @XmlElement
    private String EmailAddress;
    @XmlElement
    private BigDecimal EquityValue;
    @XmlElement
    private BigDecimal FixedIncomeValue;
    @XmlElement
    private BigDecimal FwdFutureValue;
    @XmlElement
    private String InterestBU;
    @XmlElement
    private IncomeStatus InterestStatus;
    @XmlElement
    private String InterestStatusName;
    @XmlElement
    private String MandateName;
    @XmlElement
    private String Name;
    @XmlElement
    private BigDecimal OtherValue;
    @XmlElement
    private ClientData OwnedBy;
    @XmlElement
    private GLTData PFType;
    @XmlElement
    private Integer PortfolioID;
    @XmlElement
    private String PortfolioStatus;
    @XmlElement
    private CountryData Residency;
    @XmlElement
    private GLTData RiskProfile;
    @XmlElement
    private Integer Status;
    @XmlElement
    private BigDecimal TotalValue;
    @XmlElement
    private Integer Version;

    public PortfolioData() {
    }
    
    public PortfolioData(Integer CBalID, String DefaultAddress, BigDecimal FixedIncomeValue, IncomeStatus DividendStatus, BigDecimal OtherValue, String MandateName, String Name, BigDecimal TotalValue, Integer Version, GLTData PFType, BigDecimal CashValue, CurrencyData Currency, Integer PortfolioID, String InterestBU, BigDecimal FwdFutureValue, Integer Status, BigDecimal EquityValue, ClientData OwnedBy, BigDecimal CurrentRate, String DRPStatus, CountryData Address3, AdvisorData Advisor, GLTData AccountType, Integer Default, String Code, String EmailAddress, GLTData Brand, String DividendStatusName, String PortfolioStatus, OrganisationData Custodian, CountryData Residency, IncomeStatus InterestStatus, CountryData Country, GLTData RiskProfile, String InterestStatusName, String BranchCode) {
        this.CBalID = CBalID;
        this.DefaultAddress = DefaultAddress;
        this.FixedIncomeValue = FixedIncomeValue;
        this.DividendStatus = DividendStatus;
        this.OtherValue = OtherValue;
        this.MandateName = MandateName;
        this.Name = Name;
        this.TotalValue = TotalValue;
        this.Version = Version;
        this.PFType = PFType;
        this.CashValue = CashValue;
        this.Currency = Currency;
        this.PortfolioID = PortfolioID;
        this.InterestBU = InterestBU;
        this.FwdFutureValue = FwdFutureValue;
        this.Status = Status;
        this.EquityValue = EquityValue;
        this.OwnedBy = OwnedBy;
        this.CurrentRate = CurrentRate;
        this.DRPStatus = DRPStatus;
        this.Address3 = Address3;
        this.Advisor = Advisor;
        this.AccountType = AccountType;
        this.Default = Default;
        this.Code = Code;
        this.EmailAddress = EmailAddress;
        this.Brand = Brand;
        this.DividendStatusName = DividendStatusName;
        this.PortfolioStatus = PortfolioStatus;
        this.Custodian = Custodian;
        this.Residency = Residency;
        this.InterestStatus = InterestStatus;
        this.Country = Country;
        this.RiskProfile = RiskProfile;
        this.InterestStatusName = InterestStatusName;
        this.BranchCode = BranchCode;
    }
    
    public PortfolioData(Integer CBalID, GLTData Brand, String MandateName, BigDecimal FwdFutureValue, ClientData OwnedBy, OrganisationData Custodian, CountryData Address3, BigDecimal CurrentRate, String EmailAddress, Integer Version, String InterestStatusName, GLTData AccountType, Integer Default, IncomeStatus DividendStatus, BigDecimal FixedIncomeValue, BigDecimal EquityValue, String DefaultAddress, String DividendStatusName, BigDecimal TotalValue, String Name, IncomeStatus InterestStatus, BigDecimal CashValue, BigDecimal OtherValue, AdvisorData Advisor, Integer PortfolioID, CountryData Residency, String PortfolioStatus, CountryData Country, String Code, Integer Status, CurrencyData Currency, String BranchCode, String InterestBU, GLTData PFType, String DRPStatus, GLTData RiskProfile) {
        this.CBalID = CBalID;
        this.Brand = Brand;
        this.MandateName = MandateName;
        this.FwdFutureValue = FwdFutureValue;
        this.OwnedBy = OwnedBy;
        this.Custodian = Custodian;
        this.Address3 = Address3;
        this.CurrentRate = CurrentRate;
        this.EmailAddress = EmailAddress;
        this.Version = Version;
        this.InterestStatusName = InterestStatusName;
        this.AccountType = AccountType;
        this.Default = Default;
        this.DividendStatus = DividendStatus;
        this.FixedIncomeValue = FixedIncomeValue;
        this.EquityValue = EquityValue;
        this.DefaultAddress = DefaultAddress;
        this.DividendStatusName = DividendStatusName;
        this.TotalValue = TotalValue;
        this.Name = Name;
        this.InterestStatus = InterestStatus;
        this.CashValue = CashValue;
        this.OtherValue = OtherValue;
        this.Advisor = Advisor;
        this.PortfolioID = PortfolioID;
        this.Residency = Residency;
        this.PortfolioStatus = PortfolioStatus;
        this.Country = Country;
        this.Code = Code;
        this.Status = Status;
        this.Currency = Currency;
        this.BranchCode = BranchCode;
        this.InterestBU = InterestBU;
        this.PFType = PFType;
        this.DRPStatus = DRPStatus;
        this.RiskProfile = RiskProfile;
    }

    public GLTData getAccountType() {
        return this.AccountType;
    }
    
    public void setAccountType(GLTData AccountType) {
        this.AccountType = AccountType;
    }

    public CountryData getAddress3() {
        return this.Address3;
    }
    
    public void setAddress3(CountryData Address3) {
        this.Address3 = Address3;
    }

    public AdvisorData getAdvisor() {
        return this.Advisor;
    }
    
    public void setAdvisor(AdvisorData Advisor) {
        this.Advisor = Advisor;
    }

    public String getBranchCode() {
        return this.BranchCode;
    }
    
    public void setBranchCode(String BranchCode) {
        this.BranchCode = BranchCode;
    }

    public GLTData getBrand() {
        return this.Brand;
    }
    
    public void setBrand(GLTData Brand) {
        this.Brand = Brand;
    }

    public Integer getCBalID() {
        return this.CBalID;
    }
    
    public void setCBalID(Integer CBalID) {
        this.CBalID = CBalID;
    }

    public BigDecimal getCashValue() {
        return this.CashValue;
    }
    
    public void setCashValue(BigDecimal CashValue) {
        this.CashValue = CashValue;
    }

    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    public CountryData getCountry() {
        return this.Country;
    }
    
    public void setCountry(CountryData Country) {
        this.Country = Country;
    }

    public CurrencyData getCurrency() {
        return this.Currency;
    }
    
    public void setCurrency(CurrencyData Currency) {
        this.Currency = Currency;
    }

    public BigDecimal getCurrentRate() {
        return this.CurrentRate;
    }
    
    public void setCurrentRate(BigDecimal CurrentRate) {
        this.CurrentRate = CurrentRate;
    }

    public OrganisationData getCustodian() {
        return this.Custodian;
    }
    
    public void setCustodian(OrganisationData Custodian) {
        this.Custodian = Custodian;
    }

    public String getDRPStatus() {
        return this.DRPStatus;
    }
    
    public void setDRPStatus(String DRPStatus) {
        this.DRPStatus = DRPStatus;
    }

    public Integer getDefault() {
        return this.Default;
    }
    
    public void setDefault(Integer Default) {
        this.Default = Default;
    }

    public String getDefaultAddress() {
        return this.DefaultAddress;
    }
    
    public void setDefaultAddress(String DefaultAddress) {
        this.DefaultAddress = DefaultAddress;
    }

    public IncomeStatus getDividendStatus() {
        return this.DividendStatus;
    }
    
    public void setDividendStatus(IncomeStatus DividendStatus) {
        this.DividendStatus = DividendStatus;
    }

    public String getDividendStatusName() {
        return this.DividendStatusName;
    }
    
    public void setDividendStatusName(String DividendStatusName) {
        this.DividendStatusName = DividendStatusName;
    }

    public String getEmailAddress() {
        return this.EmailAddress;
    }
    
    public void setEmailAddress(String EmailAddress) {
        this.EmailAddress = EmailAddress;
    }

    public BigDecimal getEquityValue() {
        return this.EquityValue;
    }
    
    public void setEquityValue(BigDecimal EquityValue) {
        this.EquityValue = EquityValue;
    }

    public BigDecimal getFixedIncomeValue() {
        return this.FixedIncomeValue;
    }
    
    public void setFixedIncomeValue(BigDecimal FixedIncomeValue) {
        this.FixedIncomeValue = FixedIncomeValue;
    }

    public BigDecimal getFwdFutureValue() {
        return this.FwdFutureValue;
    }
    
    public void setFwdFutureValue(BigDecimal FwdFutureValue) {
        this.FwdFutureValue = FwdFutureValue;
    }

    public String getInterestBU() {
        return this.InterestBU;
    }
    
    public void setInterestBU(String InterestBU) {
        this.InterestBU = InterestBU;
    }

    public IncomeStatus getInterestStatus() {
        return this.InterestStatus;
    }
    
    public void setInterestStatus(IncomeStatus InterestStatus) {
        this.InterestStatus = InterestStatus;
    }

    public String getInterestStatusName() {
        return this.InterestStatusName;
    }
    
    public void setInterestStatusName(String InterestStatusName) {
        this.InterestStatusName = InterestStatusName;
    }

    public String getMandateName() {
        return this.MandateName;
    }
    
    public void setMandateName(String MandateName) {
        this.MandateName = MandateName;
    }

    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    public BigDecimal getOtherValue() {
        return this.OtherValue;
    }
    
    public void setOtherValue(BigDecimal OtherValue) {
        this.OtherValue = OtherValue;
    }

    public ClientData getOwnedBy() {
        return this.OwnedBy;
    }
    
    public void setOwnedBy(ClientData OwnedBy) {
        this.OwnedBy = OwnedBy;
    }

    public GLTData getPFType() {
        return this.PFType;
    }
    
    public void setPFType(GLTData PFType) {
        this.PFType = PFType;
    }

    public Integer getPortfolioID() {
        return this.PortfolioID;
    }
    
    public void setPortfolioID(Integer PortfolioID) {
        this.PortfolioID = PortfolioID;
    }

    public String getPortfolioStatus() {
        return this.PortfolioStatus;
    }
    
    public void setPortfolioStatus(String PortfolioStatus) {
        this.PortfolioStatus = PortfolioStatus;
    }

    public CountryData getResidency() {
        return this.Residency;
    }
    
    public void setResidency(CountryData Residency) {
        this.Residency = Residency;
    }

    public GLTData getRiskProfile() {
        return this.RiskProfile;
    }
    
    public void setRiskProfile(GLTData RiskProfile) {
        this.RiskProfile = RiskProfile;
    }

    public Integer getStatus() {
        return this.Status;
    }
    
    public void setStatus(Integer Status) {
        this.Status = Status;
    }

    public BigDecimal getTotalValue() {
        return this.TotalValue;
    }
    
    public void setTotalValue(BigDecimal TotalValue) {
        this.TotalValue = TotalValue;
    }

    public Integer getVersion() {
        return this.Version;
    }
    
    public void setVersion(Integer Version) {
        this.Version = Version;
    }

}