package com.cip.transactions;

import java.math.BigDecimal;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionData")
public class TransactionData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   @XmlElement
   private BigDecimal AccruedInterest;
   @XmlElement
   private Boolean Amendment;
   @XmlElement
   private BigDecimal ApplicationMoney;
   @XmlElement
   private AssetData Asset;
   @XmlElement
   private Integer AssetID;
   @XmlElement
   private String AssetName;
   @XmlElement
   private String AssetSimplified;
   @XmlElement
   private String AssetType;
   @XmlElement
   private Integer AuditID;
   @XmlElement
   private BigDecimal BaseFXRate;
   @XmlElement
   private BigDecimal BaseFxRateInMarketConvention;
   @XmlElement
   private String BrokerID;
   @XmlElement
   private BigDecimal Brokerage;
   @XmlElement
   private AssetData CashAsset;
   @XmlElement
   private Integer CashAssetID;
   @XmlElement
   private String CashAssetSimplified;
   @XmlElement
   private BigDecimal CashEffect;
   @XmlElement
   private BigDecimal CashFXRate;
   @XmlElement
   private String ChangeReason;
   @XmlElement
   private String Comment;
   @XmlElement
   private String Commission;
   @XmlElement
   private BigDecimal CouponRate;
   @XmlElement
   private CurrencyData Currency;
   @XmlElement
   private String CurrencyName;
   @XmlElement
   private OrganisationData Custodian;
   @XmlElement
   private Integer CustodianID;
   @XmlElement
   private String CustodianName;
   @XmlElement
   private DataProviderData DataProvider;
   @XmlElement
   private Date Datestamp;
   @XmlElement
   private Integer DealerID;
   @XmlElement
   private BigDecimal DistinctPortfolio;
   @XmlElement
   private CurrencyData DividendCurrency;
   @XmlElement
   private Integer DividendCurrencyID;
   @XmlElement
   private String DividendCurrencyName;
   @XmlElement
   private GLTData DividendType;
   @XmlElement
   private Integer DividendTypeID;
   @XmlElement
   private String DividendTypeName;
   @XmlElement
   private BigDecimal EntitlementPosition;
   @XmlElement
   private String ExchangeSimplified;
   @XmlElement
   private BigDecimal ExtMarketValue;
   @XmlElement
   private String ExtRef1;
   @XmlElement
   private String ExtRef2;
   @XmlElement
   private BigDecimal FXRate;
   @XmlElement
   private BigDecimal FeeDiscount;
   @XmlElement
   private BigDecimal FormattedPrice;
   @XmlElement
   private BigDecimal FormattedPriceInMarketConvention;
   @XmlElement
   private BigDecimal FrankingCredit;
   @XmlElement
   private String FrankingCreditType;
   @XmlElement
   private BigDecimal FxRateInMarketConvention;
   @XmlElement
   private GLTData HoldingType;
   @XmlElement
   private String HoldingTypeCode;
   @XmlElement
   private Integer HoldingTypeID;
   @XmlElement
   private String HoldingTypeName;
   @XmlElement
   private String ISOCode;
   @XmlElement
   private Boolean IsAmended;
   @XmlElement
   private Boolean IsAmendment;
   @XmlElement
   private Boolean IsBuy;
   @XmlElement
   private Boolean IsCashAffected;
   @XmlElement
   private Boolean IsCashAffectedAllowingUntraded;
   @XmlElement
   private Boolean IsCashCostAffected;
   @XmlElement
   private Boolean IsContribution;
   @XmlElement
   private Boolean IsCoupon;
   @XmlElement
   private Boolean IsCrossCurrencyTrade;
   @XmlElement
   private Boolean IsDiaryDeposit;
   @XmlElement
   private Boolean IsDiaryWithdrawal;
   @XmlElement
   private Boolean IsDividend;
   @XmlElement
   private Boolean IsExpense;
   @XmlElement
   private Boolean IsFee;
   @XmlElement
   private Boolean IsFeeRebate;
   @XmlElement
   private Boolean IsForwardFXTransaction;
   @XmlElement
   private Boolean IsHedge;
   @XmlElement
   private Boolean IsIncome;
   @XmlElement
   private Boolean IsInterest;
   @XmlElement
   private Boolean IsNominalAffected;
   @XmlElement
   private Boolean IsProjected;
   @XmlElement
   private Boolean IsProposed;
   @XmlElement
   private Boolean IsSSCorSSDTrn;
   @XmlElement
   private Boolean IsSell;
   @XmlElement
   private Boolean IsSettlementProcessed;
   @XmlElement
   private Boolean IsSold;
   @XmlElement
   private Boolean IsSpotFXTransaction;
   @XmlElement
   private Boolean IsTaxRebate;
   @XmlElement
   private Boolean IsTraded;
   @XmlElement
   private Boolean IsTransferIn;
   @XmlElement
   private Boolean IsTransferOut;
   @XmlElement
   private Boolean IsUntraded;
   @XmlElement
   private Boolean IsWithdrawl;
   @XmlElement
   private String IsinSimplified;
   @XmlElement
   private Integer Lot;
   @XmlElement
   private Integer LotNo;
   @XmlElement
   private Date MaturityDate;
   @XmlElement
   private Integer MessageStatus;
   @XmlElement
   private BigDecimal Nominal;
   @XmlElement
   private BigDecimal NominalQty;
   @XmlElement
   private BigDecimal OpenCash;
   @XmlElement
   private BigDecimal OpenStock;
   @XmlElement
   private BigDecimal OpeningBasis;
   @XmlElement
   private Integer OrderID;
   @XmlElement
   private BigDecimal OtherCharge;
   @XmlElement
   private GLTData PaymentBasis;
   @XmlElement
   private Integer PaymentBasisID;
   @XmlElement
   private String PaymentBasisName;
   @XmlElement
   private PortfolioData Portfolio;
   @XmlElement
   private Integer PortfolioID;
   @XmlElement
   private Date PostedDate;
   @XmlElement
   private BigDecimal Price;
   @XmlElement
   private String Registration;
   @XmlElement
   private BigDecimal RepoAmount;
   @XmlElement
   private AssetData RepoAsset;
   @XmlElement
   private Integer RepoAssetID;
   @XmlElement
   private String RepoAssetSimplified;
   @XmlElement
   private BigDecimal RwtCustodian;
   @XmlElement
   private BigDecimal RwtRegistry;
   @XmlElement
   private BigDecimal SalesTax;
   @XmlElement
   private String SedolSimplified;
   @XmlElement
   private Date SettleDate;
   @XmlElement
   private BigDecimal StampDuty;
   @XmlElement
   private String TRNDataProviderName;
   @XmlElement
   private Integer TRNGroupID;
   @XmlElement
   private Integer TRNID;
   @XmlElement
   private Integer Time;
   @XmlElement
   private Date TradeDate;
   @XmlElement
   private BigDecimal TransAmount;
   @XmlElement
   private Integer TransMasterID;
   @XmlElement
   private GLTData TransStatus;
   @XmlElement
   private String TransStatusCode;
   @XmlElement
   private String TransStatusName;
   @XmlElement
   private GLTData TransType;
   @XmlElement
   private String TransTypeCode;
   @XmlElement
   private Integer TransTypeID;
   @XmlElement
   private String TransTypeName;
   @XmlElement
   private BigDecimal TrnAmount;
   @XmlElement
   private GLTData TrnStatus;
   @XmlElement
   private String TrnStatusName;
   @XmlElement
   private GLTData TrnType;
   @XmlElement
   private String TrnTypeName;
   @XmlElement
   private BigDecimal Wht;
   @XmlElement
   private BigDecimal WitholdingTax;
   @XmlElement
   private Boolean isActive;
   @XmlElement
   private Integer settleTradeDateDifferent;
   @XmlElement
   private String side;

   public TransactionData()
   {
   }

   public BigDecimal getAccruedInterest()
   {
      return this.AccruedInterest;
   }

   public void setAccruedInterest(BigDecimal AccruedInterest)
   {
      this.AccruedInterest = AccruedInterest;
   }

   public Boolean getAmendment()
   {
      return this.Amendment;
   }

   public void setAmendment(Boolean Amendment)
   {
      this.Amendment = Amendment;
   }

   public BigDecimal getApplicationMoney()
   {
      return this.ApplicationMoney;
   }

   public void setApplicationMoney(BigDecimal ApplicationMoney)
   {
      this.ApplicationMoney = ApplicationMoney;
   }

   public AssetData getAsset()
   {
      return this.Asset;
   }

   public void setAsset(AssetData Asset)
   {
      this.Asset = Asset;
   }

   public Integer getAssetID()
   {
      return this.AssetID;
   }

   public void setAssetID(Integer AssetID)
   {
      this.AssetID = AssetID;
   }

   public String getAssetName()
   {
      return this.AssetName;
   }

   public void setAssetName(String AssetName)
   {
      this.AssetName = AssetName;
   }

   public String getAssetSimplified()
   {
      return this.AssetSimplified;
   }

   public void setAssetSimplified(String AssetSimplified)
   {
      this.AssetSimplified = AssetSimplified;
   }

   public String getAssetType()
   {
      return this.AssetType;
   }

   public void setAssetType(String AssetType)
   {
      this.AssetType = AssetType;
   }

   public Integer getAuditID()
   {
      return this.AuditID;
   }

   public void setAuditID(Integer AuditID)
   {
      this.AuditID = AuditID;
   }

   public BigDecimal getBaseFXRate()
   {
      return this.BaseFXRate;
   }

   public void setBaseFXRate(BigDecimal BaseFXRate)
   {
      this.BaseFXRate = BaseFXRate;
   }

   public BigDecimal getBaseFxRateInMarketConvention()
   {
      return this.BaseFxRateInMarketConvention;
   }

   public void setBaseFxRateInMarketConvention(BigDecimal BaseFxRateInMarketConvention)
   {
      this.BaseFxRateInMarketConvention = BaseFxRateInMarketConvention;
   }

   public String getBrokerID()
   {
      return this.BrokerID;
   }

   public void setBrokerID(String BrokerID)
   {
      this.BrokerID = BrokerID;
   }

   public BigDecimal getBrokerage()
   {
      return this.Brokerage;
   }

   public void setBrokerage(BigDecimal Brokerage)
   {
      this.Brokerage = Brokerage;
   }

   public AssetData getCashAsset()
   {
      return this.CashAsset;
   }

   public void setCashAsset(AssetData CashAsset)
   {
      this.CashAsset = CashAsset;
   }

   public Integer getCashAssetID()
   {
      return this.CashAssetID;
   }

   public void setCashAssetID(Integer CashAssetID)
   {
      this.CashAssetID = CashAssetID;
   }

   public String getCashAssetSimplified()
   {
      return this.CashAssetSimplified;
   }

   public void setCashAssetSimplified(String CashAssetSimplified)
   {
      this.CashAssetSimplified = CashAssetSimplified;
   }

   public BigDecimal getCashEffect()
   {
      return this.CashEffect;
   }

   public void setCashEffect(BigDecimal CashEffect)
   {
      this.CashEffect = CashEffect;
   }

   public BigDecimal getCashFXRate()
   {
      return this.CashFXRate;
   }

   public void setCashFXRate(BigDecimal CashFXRate)
   {
      this.CashFXRate = CashFXRate;
   }

   public String getChangeReason()
   {
      return this.ChangeReason;
   }

   public void setChangeReason(String ChangeReason)
   {
      this.ChangeReason = ChangeReason;
   }

   public String getComment()
   {
      return this.Comment;
   }

   public void setComment(String Comment)
   {
      this.Comment = Comment;
   }

   public String getCommission()
   {
      return this.Commission;
   }

   public void setCommission(String Commission)
   {
      this.Commission = Commission;
   }

   public BigDecimal getCouponRate()
   {
      return this.CouponRate;
   }

   public void setCouponRate(BigDecimal CouponRate)
   {
      this.CouponRate = CouponRate;
   }

   public CurrencyData getCurrency()
   {
      return this.Currency;
   }

   public void setCurrency(CurrencyData Currency)
   {
      this.Currency = Currency;
   }

   public String getCurrencyName()
   {
      return this.CurrencyName;
   }

   public void setCurrencyName(String CurrencyName)
   {
      this.CurrencyName = CurrencyName;
   }

   public OrganisationData getCustodian()
   {
      return this.Custodian;
   }

   public void setCustodian(OrganisationData Custodian)
   {
      this.Custodian = Custodian;
   }

   public Integer getCustodianID()
   {
      return this.CustodianID;
   }

   public void setCustodianID(Integer CustodianID)
   {
      this.CustodianID = CustodianID;
   }

   public String getCustodianName()
   {
      return this.CustodianName;
   }

   public void setCustodianName(String CustodianName)
   {
      this.CustodianName = CustodianName;
   }

   public DataProviderData getDataProvider()
   {
      return this.DataProvider;
   }

   public void setDataProvider(DataProviderData DataProvider)
   {
      this.DataProvider = DataProvider;
   }

   public Date getDatestamp()
   {
      return this.Datestamp;
   }

   public void setDatestamp(Date Datestamp)
   {
      this.Datestamp = Datestamp;
   }

   public Integer getDealerID()
   {
      return this.DealerID;
   }

   public void setDealerID(Integer DealerID)
   {
      this.DealerID = DealerID;
   }

   public BigDecimal getDistinctPortfolio()
   {
      return this.DistinctPortfolio;
   }

   public void setDistinctPortfolio(BigDecimal DistinctPortfolio)
   {
      this.DistinctPortfolio = DistinctPortfolio;
   }

   public CurrencyData getDividendCurrency()
   {
      return this.DividendCurrency;
   }

   public void setDividendCurrency(CurrencyData DividendCurrency)
   {
      this.DividendCurrency = DividendCurrency;
   }

   public Integer getDividendCurrencyID()
   {
      return this.DividendCurrencyID;
   }

   public void setDividendCurrencyID(Integer DividendCurrencyID)
   {
      this.DividendCurrencyID = DividendCurrencyID;
   }

   public String getDividendCurrencyName()
   {
      return this.DividendCurrencyName;
   }

   public void setDividendCurrencyName(String DividendCurrencyName)
   {
      this.DividendCurrencyName = DividendCurrencyName;
   }

   public GLTData getDividendType()
   {
      return this.DividendType;
   }

   public void setDividendType(GLTData DividendType)
   {
      this.DividendType = DividendType;
   }

   public Integer getDividendTypeID()
   {
      return this.DividendTypeID;
   }

   public void setDividendTypeID(Integer DividendTypeID)
   {
      this.DividendTypeID = DividendTypeID;
   }

   public String getDividendTypeName()
   {
      return this.DividendTypeName;
   }

   public void setDividendTypeName(String DividendTypeName)
   {
      this.DividendTypeName = DividendTypeName;
   }

   public BigDecimal getEntitlementPosition()
   {
      return this.EntitlementPosition;
   }

   public void setEntitlementPosition(BigDecimal EntitlementPosition)
   {
      this.EntitlementPosition = EntitlementPosition;
   }

   public String getExchangeSimplified()
   {
      return this.ExchangeSimplified;
   }

   public void setExchangeSimplified(String ExchangeSimplified)
   {
      this.ExchangeSimplified = ExchangeSimplified;
   }

   public BigDecimal getExtMarketValue()
   {
      return this.ExtMarketValue;
   }

   public void setExtMarketValue(BigDecimal ExtMarketValue)
   {
      this.ExtMarketValue = ExtMarketValue;
   }

   public String getExtRef1()
   {
      return this.ExtRef1;
   }

   public void setExtRef1(String ExtRef1)
   {
      this.ExtRef1 = ExtRef1;
   }

   public String getExtRef2()
   {
      return this.ExtRef2;
   }

   public void setExtRef2(String ExtRef2)
   {
      this.ExtRef2 = ExtRef2;
   }

   public BigDecimal getFXRate()
   {
      return this.FXRate;
   }

   public void setFXRate(BigDecimal FXRate)
   {
      this.FXRate = FXRate;
   }

   public BigDecimal getFeeDiscount()
   {
      return this.FeeDiscount;
   }

   public void setFeeDiscount(BigDecimal FeeDiscount)
   {
      this.FeeDiscount = FeeDiscount;
   }

   public BigDecimal getFormattedPrice()
   {
      return this.FormattedPrice;
   }

   public void setFormattedPrice(BigDecimal FormattedPrice)
   {
      this.FormattedPrice = FormattedPrice;
   }

   public BigDecimal getFormattedPriceInMarketConvention()
   {
      return this.FormattedPriceInMarketConvention;
   }

   public void setFormattedPriceInMarketConvention(BigDecimal FormattedPriceInMarketConvention)
   {
      this.FormattedPriceInMarketConvention = FormattedPriceInMarketConvention;
   }

   public BigDecimal getFrankingCredit()
   {
      return this.FrankingCredit;
   }

   public void setFrankingCredit(BigDecimal FrankingCredit)
   {
      this.FrankingCredit = FrankingCredit;
   }

   public String getFrankingCreditType()
   {
      return this.FrankingCreditType;
   }

   public void setFrankingCreditType(String FrankingCreditType)
   {
      this.FrankingCreditType = FrankingCreditType;
   }

   public BigDecimal getFxRateInMarketConvention()
   {
      return this.FxRateInMarketConvention;
   }

   public void setFxRateInMarketConvention(BigDecimal FxRateInMarketConvention)
   {
      this.FxRateInMarketConvention = FxRateInMarketConvention;
   }

   public GLTData getHoldingType()
   {
      return this.HoldingType;
   }

   public void setHoldingType(GLTData HoldingType)
   {
      this.HoldingType = HoldingType;
   }

   public String getHoldingTypeCode()
   {
      return this.HoldingTypeCode;
   }

   public void setHoldingTypeCode(String HoldingTypeCode)
   {
      this.HoldingTypeCode = HoldingTypeCode;
   }

   public Integer getHoldingTypeID()
   {
      return this.HoldingTypeID;
   }

   public void setHoldingTypeID(Integer HoldingTypeID)
   {
      this.HoldingTypeID = HoldingTypeID;
   }

   public String getHoldingTypeName()
   {
      return this.HoldingTypeName;
   }

   public void setHoldingTypeName(String HoldingTypeName)
   {
      this.HoldingTypeName = HoldingTypeName;
   }

   public String getISOCode()
   {
      return this.ISOCode;
   }

   public void setISOCode(String ISOCode)
   {
      this.ISOCode = ISOCode;
   }

   public Boolean getIsAmended()
   {
      return this.IsAmended;
   }

   public void setIsAmended(Boolean IsAmended)
   {
      this.IsAmended = IsAmended;
   }

   public Boolean getIsAmendment()
   {
      return this.IsAmendment;
   }

   public void setIsAmendment(Boolean IsAmendment)
   {
      this.IsAmendment = IsAmendment;
   }

   public Boolean getIsBuy()
   {
      return this.IsBuy;
   }

   public void setIsBuy(Boolean IsBuy)
   {
      this.IsBuy = IsBuy;
   }

   public Boolean getIsCashAffected()
   {
      return this.IsCashAffected;
   }

   public void setIsCashAffected(Boolean IsCashAffected)
   {
      this.IsCashAffected = IsCashAffected;
   }

   public Boolean getIsCashAffectedAllowingUntraded()
   {
      return this.IsCashAffectedAllowingUntraded;
   }

   public void setIsCashAffectedAllowingUntraded(Boolean IsCashAffectedAllowingUntraded)
   {
      this.IsCashAffectedAllowingUntraded = IsCashAffectedAllowingUntraded;
   }

   public Boolean getIsCashCostAffected()
   {
      return this.IsCashCostAffected;
   }

   public void setIsCashCostAffected(Boolean IsCashCostAffected)
   {
      this.IsCashCostAffected = IsCashCostAffected;
   }

   public Boolean getIsContribution()
   {
      return this.IsContribution;
   }

   public void setIsContribution(Boolean IsContribution)
   {
      this.IsContribution = IsContribution;
   }

   public Boolean getIsCoupon()
   {
      return this.IsCoupon;
   }

   public void setIsCoupon(Boolean IsCoupon)
   {
      this.IsCoupon = IsCoupon;
   }

   public Boolean getIsCrossCurrencyTrade()
   {
      return this.IsCrossCurrencyTrade;
   }

   public void setIsCrossCurrencyTrade(Boolean IsCrossCurrencyTrade)
   {
      this.IsCrossCurrencyTrade = IsCrossCurrencyTrade;
   }

   public Boolean getIsDiaryDeposit()
   {
      return this.IsDiaryDeposit;
   }

   public void setIsDiaryDeposit(Boolean IsDiaryDeposit)
   {
      this.IsDiaryDeposit = IsDiaryDeposit;
   }

   public Boolean getIsDiaryWithdrawal()
   {
      return this.IsDiaryWithdrawal;
   }

   public void setIsDiaryWithdrawal(Boolean IsDiaryWithdrawal)
   {
      this.IsDiaryWithdrawal = IsDiaryWithdrawal;
   }

   public Boolean getIsDividend()
   {
      return this.IsDividend;
   }

   public void setIsDividend(Boolean IsDividend)
   {
      this.IsDividend = IsDividend;
   }

   public Boolean getIsExpense()
   {
      return this.IsExpense;
   }

   public void setIsExpense(Boolean IsExpense)
   {
      this.IsExpense = IsExpense;
   }

   public Boolean getIsFee()
   {
      return this.IsFee;
   }

   public void setIsFee(Boolean IsFee)
   {
      this.IsFee = IsFee;
   }

   public Boolean getIsFeeRebate()
   {
      return this.IsFeeRebate;
   }

   public void setIsFeeRebate(Boolean IsFeeRebate)
   {
      this.IsFeeRebate = IsFeeRebate;
   }

   public Boolean getIsForwardFXTransaction()
   {
      return this.IsForwardFXTransaction;
   }

   public void setIsForwardFXTransaction(Boolean IsForwardFXTransaction)
   {
      this.IsForwardFXTransaction = IsForwardFXTransaction;
   }

   public Boolean getIsHedge()
   {
      return this.IsHedge;
   }

   public void setIsHedge(Boolean IsHedge)
   {
      this.IsHedge = IsHedge;
   }

   public Boolean getIsIncome()
   {
      return this.IsIncome;
   }

   public void setIsIncome(Boolean IsIncome)
   {
      this.IsIncome = IsIncome;
   }

   public Boolean getIsInterest()
   {
      return this.IsInterest;
   }

   public void setIsInterest(Boolean IsInterest)
   {
      this.IsInterest = IsInterest;
   }

   public Boolean getIsNominalAffected()
   {
      return this.IsNominalAffected;
   }

   public void setIsNominalAffected(Boolean IsNominalAffected)
   {
      this.IsNominalAffected = IsNominalAffected;
   }

   public Boolean getIsProjected()
   {
      return this.IsProjected;
   }

   public void setIsProjected(Boolean IsProjected)
   {
      this.IsProjected = IsProjected;
   }

   public Boolean getIsProposed()
   {
      return this.IsProposed;
   }

   public void setIsProposed(Boolean IsProposed)
   {
      this.IsProposed = IsProposed;
   }

   public Boolean getIsSSCorSSDTrn()
   {
      return this.IsSSCorSSDTrn;
   }

   public void setIsSSCorSSDTrn(Boolean IsSSCorSSDTrn)
   {
      this.IsSSCorSSDTrn = IsSSCorSSDTrn;
   }

   public Boolean getIsSell()
   {
      return this.IsSell;
   }

   public void setIsSell(Boolean IsSell)
   {
      this.IsSell = IsSell;
   }

   public Boolean getIsSettlementProcessed()
   {
      return this.IsSettlementProcessed;
   }

   public void setIsSettlementProcessed(Boolean IsSettlementProcessed)
   {
      this.IsSettlementProcessed = IsSettlementProcessed;
   }

   public Boolean getIsSold()
   {
      return this.IsSold;
   }

   public void setIsSold(Boolean IsSold)
   {
      this.IsSold = IsSold;
   }

   public Boolean getIsSpotFXTransaction()
   {
      return this.IsSpotFXTransaction;
   }

   public void setIsSpotFXTransaction(Boolean IsSpotFXTransaction)
   {
      this.IsSpotFXTransaction = IsSpotFXTransaction;
   }

   public Boolean getIsTaxRebate()
   {
      return this.IsTaxRebate;
   }

   public void setIsTaxRebate(Boolean IsTaxRebate)
   {
      this.IsTaxRebate = IsTaxRebate;
   }

   public Boolean getIsTraded()
   {
      return this.IsTraded;
   }

   public void setIsTraded(Boolean IsTraded)
   {
      this.IsTraded = IsTraded;
   }

   public Boolean getIsTransferIn()
   {
      return this.IsTransferIn;
   }

   public void setIsTransferIn(Boolean IsTransferIn)
   {
      this.IsTransferIn = IsTransferIn;
   }

   public Boolean getIsTransferOut()
   {
      return this.IsTransferOut;
   }

   public void setIsTransferOut(Boolean IsTransferOut)
   {
      this.IsTransferOut = IsTransferOut;
   }

   public Boolean getIsUntraded()
   {
      return this.IsUntraded;
   }

   public void setIsUntraded(Boolean IsUntraded)
   {
      this.IsUntraded = IsUntraded;
   }

   public Boolean getIsWithdrawl()
   {
      return this.IsWithdrawl;
   }

   public void setIsWithdrawl(Boolean IsWithdrawl)
   {
      this.IsWithdrawl = IsWithdrawl;
   }

   public String getIsinSimplified()
   {
      return this.IsinSimplified;
   }

   public void setIsinSimplified(String IsinSimplified)
   {
      this.IsinSimplified = IsinSimplified;
   }

   public Integer getLot()
   {
      return this.Lot;
   }

   public void setLot(Integer Lot)
   {
      this.Lot = Lot;
   }

   public Integer getLotNo()
   {
      return this.LotNo;
   }

   public void setLotNo(Integer LotNo)
   {
      this.LotNo = LotNo;
   }

   public Date getMaturityDate()
   {
      return this.MaturityDate;
   }

   public void setMaturityDate(Date MaturityDate)
   {
      this.MaturityDate = MaturityDate;
   }

   public Integer getMessageStatus()
   {
      return this.MessageStatus;
   }

   public void setMessageStatus(Integer MessageStatus)
   {
      this.MessageStatus = MessageStatus;
   }

   public BigDecimal getNominal()
   {
      return this.Nominal;
   }

   public void setNominal(BigDecimal Nominal)
   {
      this.Nominal = Nominal;
   }

   public BigDecimal getNominalQty()
   {
      return this.NominalQty;
   }

   public void setNominalQty(BigDecimal NominalQty)
   {
      this.NominalQty = NominalQty;
   }

   public BigDecimal getOpenCash()
   {
      return this.OpenCash;
   }

   public void setOpenCash(BigDecimal OpenCash)
   {
      this.OpenCash = OpenCash;
   }

   public BigDecimal getOpenStock()
   {
      return this.OpenStock;
   }

   public void setOpenStock(BigDecimal OpenStock)
   {
      this.OpenStock = OpenStock;
   }

   public BigDecimal getOpeningBasis()
   {
      return this.OpeningBasis;
   }

   public void setOpeningBasis(BigDecimal OpeningBasis)
   {
      this.OpeningBasis = OpeningBasis;
   }

   public Integer getOrderID()
   {
      return this.OrderID;
   }

   public void setOrderID(Integer OrderID)
   {
      this.OrderID = OrderID;
   }

   public BigDecimal getOtherCharge()
   {
      return this.OtherCharge;
   }

   public void setOtherCharge(BigDecimal OtherCharge)
   {
      this.OtherCharge = OtherCharge;
   }

   public GLTData getPaymentBasis()
   {
      return this.PaymentBasis;
   }

   public void setPaymentBasis(GLTData PaymentBasis)
   {
      this.PaymentBasis = PaymentBasis;
   }

   public Integer getPaymentBasisID()
   {
      return this.PaymentBasisID;
   }

   public void setPaymentBasisID(Integer PaymentBasisID)
   {
      this.PaymentBasisID = PaymentBasisID;
   }

   public String getPaymentBasisName()
   {
      return this.PaymentBasisName;
   }

   public void setPaymentBasisName(String PaymentBasisName)
   {
      this.PaymentBasisName = PaymentBasisName;
   }

   public PortfolioData getPortfolio()
   {
      return this.Portfolio;
   }

   public void setPortfolio(PortfolioData Portfolio)
   {
      this.Portfolio = Portfolio;
   }

   public Integer getPortfolioID()
   {
      return this.PortfolioID;
   }

   public void setPortfolioID(Integer PortfolioID)
   {
      this.PortfolioID = PortfolioID;
   }

   public Date getPostedDate()
   {
      return this.PostedDate;
   }

   public void setPostedDate(Date PostedDate)
   {
      this.PostedDate = PostedDate;
   }

   public BigDecimal getPrice()
   {
      return this.Price;
   }

   public void setPrice(BigDecimal Price)
   {
      this.Price = Price;
   }

   public String getRegistration()
   {
      return this.Registration;
   }

   public void setRegistration(String Registration)
   {
      this.Registration = Registration;
   }

   public BigDecimal getRepoAmount()
   {
      return this.RepoAmount;
   }

   public void setRepoAmount(BigDecimal RepoAmount)
   {
      this.RepoAmount = RepoAmount;
   }

   public AssetData getRepoAsset()
   {
      return this.RepoAsset;
   }

   public void setRepoAsset(AssetData RepoAsset)
   {
      this.RepoAsset = RepoAsset;
   }

   public Integer getRepoAssetID()
   {
      return this.RepoAssetID;
   }

   public void setRepoAssetID(Integer RepoAssetID)
   {
      this.RepoAssetID = RepoAssetID;
   }

   public String getRepoAssetSimplified()
   {
      return this.RepoAssetSimplified;
   }

   public void setRepoAssetSimplified(String RepoAssetSimplified)
   {
      this.RepoAssetSimplified = RepoAssetSimplified;
   }

   public BigDecimal getRwtCustodian()
   {
      return this.RwtCustodian;
   }

   public void setRwtCustodian(BigDecimal RwtCustodian)
   {
      this.RwtCustodian = RwtCustodian;
   }

   public BigDecimal getRwtRegistry()
   {
      return this.RwtRegistry;
   }

   public void setRwtRegistry(BigDecimal RwtRegistry)
   {
      this.RwtRegistry = RwtRegistry;
   }

   public BigDecimal getSalesTax()
   {
      return this.SalesTax;
   }

   public void setSalesTax(BigDecimal SalesTax)
   {
      this.SalesTax = SalesTax;
   }

   public String getSedolSimplified()
   {
      return this.SedolSimplified;
   }

   public void setSedolSimplified(String SedolSimplified)
   {
      this.SedolSimplified = SedolSimplified;
   }

   public Date getSettleDate()
   {
      return this.SettleDate;
   }

   public void setSettleDate(Date SettleDate)
   {
      this.SettleDate = SettleDate;
   }

   public BigDecimal getStampDuty()
   {
      return this.StampDuty;
   }

   public void setStampDuty(BigDecimal StampDuty)
   {
      this.StampDuty = StampDuty;
   }


   public String getTRNDataProviderName() {
      return TRNDataProviderName;
   }

   public void setTRNDataProviderName(String TRNDataProviderName) {
      this.TRNDataProviderName = TRNDataProviderName;
   }

   public Integer getTRNGroupID()
   {
      return this.TRNGroupID;
   }

   public void setTRNGroupID(Integer TRNGroupID)
   {
      this.TRNGroupID = TRNGroupID;
   }

   public Integer getTRNID()
   {
      return this.TRNID;
   }

   public void setTRNID(Integer TRNID)
   {
      this.TRNID = TRNID;
   }

   public Integer getTime()
   {
      return this.Time;
   }

   public void setTime(Integer Time)
   {
      this.Time = Time;
   }

   public Date getTradeDate()
   {
      return this.TradeDate;
   }

   public void setTradeDate(Date TradeDate)
   {
      this.TradeDate = TradeDate;
   }

   public BigDecimal getTransAmount()
   {
      return this.TransAmount;
   }

   public void setTransAmount(BigDecimal TransAmount)
   {
      this.TransAmount = TransAmount;
   }

   public Integer getTransMasterID()
   {
      return this.TransMasterID;
   }

   public void setTransMasterID(Integer TransMasterID)
   {
      this.TransMasterID = TransMasterID;
   }

   public GLTData getTransStatus()
   {
      return this.TransStatus;
   }

   public void setTransStatus(GLTData TransStatus)
   {
      this.TransStatus = TransStatus;
   }

   public String getTransStatusCode()
   {
      return this.TransStatusCode;
   }

   public void setTransStatusCode(String TransStatusCode)
   {
      this.TransStatusCode = TransStatusCode;
   }

   public String getTransStatusName()
   {
      return this.TransStatusName;
   }

   public void setTransStatusName(String TransStatusName)
   {
      this.TransStatusName = TransStatusName;
   }

   public GLTData getTransType()
   {
      return this.TransType;
   }

   public void setTransType(GLTData TransType)
   {
      this.TransType = TransType;
   }

   public String getTransTypeCode()
   {
      return this.TransTypeCode;
   }

   public void setTransTypeCode(String TransTypeCode)
   {
      this.TransTypeCode = TransTypeCode;
   }

   public Integer getTransTypeID()
   {
      return this.TransTypeID;
   }

   public void setTransTypeID(Integer TransTypeID)
   {
      this.TransTypeID = TransTypeID;
   }

   public String getTransTypeName()
   {
      return this.TransTypeName;
   }

   public void setTransTypeName(String TransTypeName)
   {
      this.TransTypeName = TransTypeName;
   }

   public BigDecimal getTrnAmount()
   {
      return this.TrnAmount;
   }

   public void setTrnAmount(BigDecimal TrnAmount)
   {
      this.TrnAmount = TrnAmount;
   }

   public GLTData getTrnStatus()
   {
      return this.TrnStatus;
   }

   public void setTrnStatus(GLTData TrnStatus)
   {
      this.TrnStatus = TrnStatus;
   }

   public String getTrnStatusName()
   {
      return this.TrnStatusName;
   }

   public void setTrnStatusName(String TrnStatusName)
   {
      this.TrnStatusName = TrnStatusName;
   }

   public GLTData getTrnType()
   {
      return this.TrnType;
   }

   public void setTrnType(GLTData TrnType)
   {
      this.TrnType = TrnType;
   }

   public String getTrnTypeName()
   {
      return this.TrnTypeName;
   }

   public void setTrnTypeName(String TrnTypeName)
   {
      this.TrnTypeName = TrnTypeName;
   }

   public BigDecimal getWht()
   {
      return this.Wht;
   }

   public void setWht(BigDecimal Wht)
   {
      this.Wht = Wht;
   }

   public BigDecimal getWitholdingTax()
   {
      return this.WitholdingTax;
   }

   public void setWitholdingTax(BigDecimal WitholdingTax)
   {
      this.WitholdingTax = WitholdingTax;
   }

   public Boolean getIsActive()
   {
      return this.isActive;
   }

   public void setIsActive(Boolean isActive)
   {
      this.isActive = isActive;
   }

   public Integer getSettleTradeDateDifferent()
   {
      return this.settleTradeDateDifferent;
   }

   public void setSettleTradeDateDifferent(
         Integer settleTradeDateDifferent)
   {
      this.settleTradeDateDifferent = settleTradeDateDifferent;
   }

   public String getSide()
   {
      return this.side;
   }

   public void setSide(String side)
   {
      this.side = side;
   }

}