package com.cip.transactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="TransactionUI")
public class TransactionUI implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    @XmlElement
    private String AccruedInterestField;
    @XmlElement
    private String Action;
    @XmlElement
    private String ApplicationMoneyField;
    @XmlElement
    private String AssetField;
    @XmlElement
    private String BaseFXRateField;
    @XmlElement
    private String BrokerAllowed;
    @XmlElement
    private String BrokerIDField;
    @XmlElement
    private String BrokerageField;
    @XmlElement
    private Boolean CanCreate;
    @XmlElement
    private String CashEffectField;
    @XmlElement
    private String CashFXRateField;
    @XmlElement
    private String ChangeReasonField;
    @XmlElement
    private String ChargesField;
    @XmlElement
    private String CommentAllowed;
    @XmlElement
    private String CommentField;
    @XmlElement
    private String CommissionField;
    @XmlElement
    private String ConsiderationField;
    @XmlElement
    private String CouponRateField;
    @XmlElement
    private String CustodianField;
    @XmlElement
    private String DataProviderAllowed;
    @XmlElement
    private String DataProviderField;
    @XmlElement
    private String DealerIDField;
    @XmlElement
    private String DividendCurrencyField;
    @XmlElement
    private String DividendTypeField;
    @XmlElement
    private String EntitlementPositionField;
    @XmlElement
    private String ExtRef1Allowed;
    @XmlElement
    private String ExtRef1Field;
    @XmlElement
    private String ExtRef2Allowed;
    @XmlElement
    private String ExtRef2Field;
    @XmlElement
    private String FXRateField;
    @XmlElement
    private String FrankingCreditField;
    @XmlElement
    private String FrankingCreditTypeField;
    @XmlElement
    private String HoldingTypeAllowed;
    @XmlElement
    private String HoldingTypeField;
    @XmlElement
    private Boolean IsEditable;
    @XmlElement
    private String LotNoField;
    @XmlElement
    private String MaturityDateField;
    @XmlElement
    private String NominalField;
    @XmlElement
    private String OpenCashField;
    @XmlElement
    private String OpenStockField;
    @XmlElement
    private String OrderIDField;
    @XmlElement
    private String PaymentBasisField;
    @XmlElement
    private java.math.BigDecimal PriceAllowed;
    @XmlElement
    private String PriceField;
    @XmlElement
    private String RegistrationField;
    @XmlElement
    private String RepoAmountField;
    @XmlElement
    private String RepoAssetField;
    @XmlElement
    private String RwtCustodianField;
    @XmlElement
    private String RwtRegistryField;
    @XmlElement
    private String SalesTaxField;
    @XmlElement
    private String SettleCcyAllowed;
    @XmlElement
    private String SettleCurrencyAllowed;
    @XmlElement
    private String SettleCurrencyField;
    @XmlElement
    private String SettleDateField;
    @XmlElement
    private String StampDutyField;
    @XmlElement
    private String TradeDateField;
    @XmlElement
    private String TransStatusAllowed;
    @XmlElement
    private String TransStatusField;
    @XmlElement
    private String TransTypeField;
    @XmlElement
    private String TransTypesAllowed;
    @XmlElement
    private String WitholdingTaxField;

    public TransactionUI() {
    }
    
    public TransactionUI(String ExtRef2Field, String PaymentBasisField, String CustodianField, String DataProviderField, String BrokerAllowed, String EntitlementPositionField, String CouponRateField, String TransTypeField, String RegistrationField, String CashEffectField, java.math.BigDecimal PriceAllowed, String DividendCurrencyField, String ExtRef1Field, String TransTypesAllowed, String TransStatusField, String FrankingCreditTypeField, String SettleCurrencyAllowed, String OpenCashField, String CommentField, String CashFXRateField, String ApplicationMoneyField, String OpenStockField, String ExtRef1Allowed, String DataProviderAllowed, Boolean CanCreate, String TransStatusAllowed, Boolean IsEditable, String AccruedInterestField, String Action, String BrokerageField, String CommentAllowed, String BrokerIDField, String FrankingCreditField, String DealerIDField, String RwtCustodianField, String MaturityDateField, String CommissionField, String LotNoField, String WitholdingTaxField, String AssetField, String DividendTypeField, String HoldingTypeField, String PriceField, String RepoAssetField, String RepoAmountField, String StampDutyField, String OrderIDField, String NominalField, String SettleDateField, String ChargesField, String SettleCcyAllowed, String HoldingTypeAllowed, String ConsiderationField, String FXRateField, String RwtRegistryField, String SalesTaxField, String ExtRef2Allowed, String SettleCurrencyField, String BaseFXRateField, String TradeDateField, String ChangeReasonField) {
        this.ExtRef2Field = ExtRef2Field;
        this.PaymentBasisField = PaymentBasisField;
        this.CustodianField = CustodianField;
        this.DataProviderField = DataProviderField;
        this.BrokerAllowed = BrokerAllowed;
        this.EntitlementPositionField = EntitlementPositionField;
        this.CouponRateField = CouponRateField;
        this.TransTypeField = TransTypeField;
        this.RegistrationField = RegistrationField;
        this.CashEffectField = CashEffectField;
        this.PriceAllowed = PriceAllowed;
        this.DividendCurrencyField = DividendCurrencyField;
        this.ExtRef1Field = ExtRef1Field;
        this.TransTypesAllowed = TransTypesAllowed;
        this.TransStatusField = TransStatusField;
        this.FrankingCreditTypeField = FrankingCreditTypeField;
        this.SettleCurrencyAllowed = SettleCurrencyAllowed;
        this.OpenCashField = OpenCashField;
        this.CommentField = CommentField;
        this.CashFXRateField = CashFXRateField;
        this.ApplicationMoneyField = ApplicationMoneyField;
        this.OpenStockField = OpenStockField;
        this.ExtRef1Allowed = ExtRef1Allowed;
        this.DataProviderAllowed = DataProviderAllowed;
        this.CanCreate = CanCreate;
        this.TransStatusAllowed = TransStatusAllowed;
        this.IsEditable = IsEditable;
        this.AccruedInterestField = AccruedInterestField;
        this.Action = Action;
        this.BrokerageField = BrokerageField;
        this.CommentAllowed = CommentAllowed;
        this.BrokerIDField = BrokerIDField;
        this.FrankingCreditField = FrankingCreditField;
        this.DealerIDField = DealerIDField;
        this.RwtCustodianField = RwtCustodianField;
        this.MaturityDateField = MaturityDateField;
        this.CommissionField = CommissionField;
        this.LotNoField = LotNoField;
        this.WitholdingTaxField = WitholdingTaxField;
        this.AssetField = AssetField;
        this.DividendTypeField = DividendTypeField;
        this.HoldingTypeField = HoldingTypeField;
        this.PriceField = PriceField;
        this.RepoAssetField = RepoAssetField;
        this.RepoAmountField = RepoAmountField;
        this.StampDutyField = StampDutyField;
        this.OrderIDField = OrderIDField;
        this.NominalField = NominalField;
        this.SettleDateField = SettleDateField;
        this.ChargesField = ChargesField;
        this.SettleCcyAllowed = SettleCcyAllowed;
        this.HoldingTypeAllowed = HoldingTypeAllowed;
        this.ConsiderationField = ConsiderationField;
        this.FXRateField = FXRateField;
        this.RwtRegistryField = RwtRegistryField;
        this.SalesTaxField = SalesTaxField;
        this.ExtRef2Allowed = ExtRef2Allowed;
        this.SettleCurrencyField = SettleCurrencyField;
        this.BaseFXRateField = BaseFXRateField;
        this.TradeDateField = TradeDateField;
        this.ChangeReasonField = ChangeReasonField;
    }
    
    public TransactionUI(Boolean IsEditable, Boolean CanCreate, String AccruedInterestField, String ApplicationMoneyField, String AssetField, String BaseFXRateField, String BrokerageField, String BrokerIDField, String CashEffectField, String CashFXRateField, String ChangeReasonField, String ChargesField, String CommentField, String CommissionField, String ConsiderationField, String CouponRateField, String CustodianField, String DealerIDField, String DividendCurrencyField, String DividendTypeField, String EntitlementPositionField, String ExtRef1Field, String ExtRef2Field, String FrankingCreditField, String FrankingCreditTypeField, String FXRateField, String HoldingTypeAllowed, String HoldingTypeField, String LotNoField, String MaturityDateField, String NominalField, String OpenCashField, String OpenStockField, String PaymentBasisField, String PriceField, String RegistrationField, String RepoAmountField, String RepoAssetField, String RwtCustodianField, String RwtRegistryField, String SalesTaxField, String SettleCurrencyAllowed, String SettleCurrencyField, String SettleDateField, String StampDutyField, String TradeDateField, String TransStatusAllowed, String TransStatusField, String TransTypesAllowed, String TransTypeField, String WitholdingTaxField, String DataProviderField, String OrderIDField, String DataProviderAllowed, String Action, String ExtRef1Allowed, java.math.BigDecimal PriceAllowed, String BrokerAllowed, String ExtRef2Allowed, String CommentAllowed, String SettleCcyAllowed) {
        this.IsEditable = IsEditable;
        this.CanCreate = CanCreate;
        this.AccruedInterestField = AccruedInterestField;
        this.ApplicationMoneyField = ApplicationMoneyField;
        this.AssetField = AssetField;
        this.BaseFXRateField = BaseFXRateField;
        this.BrokerageField = BrokerageField;
        this.BrokerIDField = BrokerIDField;
        this.CashEffectField = CashEffectField;
        this.CashFXRateField = CashFXRateField;
        this.ChangeReasonField = ChangeReasonField;
        this.ChargesField = ChargesField;
        this.CommentField = CommentField;
        this.CommissionField = CommissionField;
        this.ConsiderationField = ConsiderationField;
        this.CouponRateField = CouponRateField;
        this.CustodianField = CustodianField;
        this.DealerIDField = DealerIDField;
        this.DividendCurrencyField = DividendCurrencyField;
        this.DividendTypeField = DividendTypeField;
        this.EntitlementPositionField = EntitlementPositionField;
        this.ExtRef1Field = ExtRef1Field;
        this.ExtRef2Field = ExtRef2Field;
        this.FrankingCreditField = FrankingCreditField;
        this.FrankingCreditTypeField = FrankingCreditTypeField;
        this.FXRateField = FXRateField;
        this.HoldingTypeAllowed = HoldingTypeAllowed;
        this.HoldingTypeField = HoldingTypeField;
        this.LotNoField = LotNoField;
        this.MaturityDateField = MaturityDateField;
        this.NominalField = NominalField;
        this.OpenCashField = OpenCashField;
        this.OpenStockField = OpenStockField;
        this.PaymentBasisField = PaymentBasisField;
        this.PriceField = PriceField;
        this.RegistrationField = RegistrationField;
        this.RepoAmountField = RepoAmountField;
        this.RepoAssetField = RepoAssetField;
        this.RwtCustodianField = RwtCustodianField;
        this.RwtRegistryField = RwtRegistryField;
        this.SalesTaxField = SalesTaxField;
        this.SettleCurrencyAllowed = SettleCurrencyAllowed;
        this.SettleCurrencyField = SettleCurrencyField;
        this.SettleDateField = SettleDateField;
        this.StampDutyField = StampDutyField;
        this.TradeDateField = TradeDateField;
        this.TransStatusAllowed = TransStatusAllowed;
        this.TransStatusField = TransStatusField;
        this.TransTypesAllowed = TransTypesAllowed;
        this.TransTypeField = TransTypeField;
        this.WitholdingTaxField = WitholdingTaxField;
        this.DataProviderField = DataProviderField;
        this.OrderIDField = OrderIDField;
        this.DataProviderAllowed = DataProviderAllowed;
        this.Action = Action;
        this.ExtRef1Allowed = ExtRef1Allowed;
        this.PriceAllowed = PriceAllowed;
        this.BrokerAllowed = BrokerAllowed;
        this.ExtRef2Allowed = ExtRef2Allowed;
        this.CommentAllowed = CommentAllowed;
        this.SettleCcyAllowed = SettleCcyAllowed;
    }

    public String getAccruedInterestField() {
        return this.AccruedInterestField;
    }
    
    public void setAccruedInterestField(String AccruedInterestField) {
        this.AccruedInterestField = AccruedInterestField;
    }

    public String getAction() {
        return this.Action;
    }
    
    public void setAction(String Action) {
        this.Action = Action;
    }

    public String getApplicationMoneyField() {
        return this.ApplicationMoneyField;
    }
    
    public void setApplicationMoneyField(String ApplicationMoneyField) {
        this.ApplicationMoneyField = ApplicationMoneyField;
    }

    public String getAssetField() {
        return this.AssetField;
    }
    
    public void setAssetField(String AssetField) {
        this.AssetField = AssetField;
    }

    public String getBaseFXRateField() {
        return this.BaseFXRateField;
    }
    
    public void setBaseFXRateField(String BaseFXRateField) {
        this.BaseFXRateField = BaseFXRateField;
    }

    public String getBrokerAllowed() {
        return this.BrokerAllowed;
    }
    
    public void setBrokerAllowed(String BrokerAllowed) {
        this.BrokerAllowed = BrokerAllowed;
    }

    public String getBrokerIDField() {
        return this.BrokerIDField;
    }
    
    public void setBrokerIDField(String BrokerIDField) {
        this.BrokerIDField = BrokerIDField;
    }

    public String getBrokerageField() {
        return this.BrokerageField;
    }
    
    public void setBrokerageField(String BrokerageField) {
        this.BrokerageField = BrokerageField;
    }

    public Boolean getCanCreate() {
        return this.CanCreate;
    }
    
    public void setCanCreate(Boolean CanCreate) {
        this.CanCreate = CanCreate;
    }

    public String getCashEffectField() {
        return this.CashEffectField;
    }
    
    public void setCashEffectField(String CashEffectField) {
        this.CashEffectField = CashEffectField;
    }

    public String getCashFXRateField() {
        return this.CashFXRateField;
    }
    
    public void setCashFXRateField(String CashFXRateField) {
        this.CashFXRateField = CashFXRateField;
    }

    public String getChangeReasonField() {
        return this.ChangeReasonField;
    }
    
    public void setChangeReasonField(String ChangeReasonField) {
        this.ChangeReasonField = ChangeReasonField;
    }

    public String getChargesField() {
        return this.ChargesField;
    }
    
    public void setChargesField(String ChargesField) {
        this.ChargesField = ChargesField;
    }

    public String getCommentAllowed() {
        return this.CommentAllowed;
    }
    
    public void setCommentAllowed(String CommentAllowed) {
        this.CommentAllowed = CommentAllowed;
    }

    public String getCommentField() {
        return this.CommentField;
    }
    
    public void setCommentField(String CommentField) {
        this.CommentField = CommentField;
    }

    public String getCommissionField() {
        return this.CommissionField;
    }
    
    public void setCommissionField(String CommissionField) {
        this.CommissionField = CommissionField;
    }

    public String getConsiderationField() {
        return this.ConsiderationField;
    }
    
    public void setConsiderationField(String ConsiderationField) {
        this.ConsiderationField = ConsiderationField;
    }

    public String getCouponRateField() {
        return this.CouponRateField;
    }
    
    public void setCouponRateField(String CouponRateField) {
        this.CouponRateField = CouponRateField;
    }

    public String getCustodianField() {
        return this.CustodianField;
    }
    
    public void setCustodianField(String CustodianField) {
        this.CustodianField = CustodianField;
    }

    public String getDataProviderAllowed() {
        return this.DataProviderAllowed;
    }
    
    public void setDataProviderAllowed(String DataProviderAllowed) {
        this.DataProviderAllowed = DataProviderAllowed;
    }

    public String getDataProviderField() {
        return this.DataProviderField;
    }
    
    public void setDataProviderField(String DataProviderField) {
        this.DataProviderField = DataProviderField;
    }

    public String getDealerIDField() {
        return this.DealerIDField;
    }
    
    public void setDealerIDField(String DealerIDField) {
        this.DealerIDField = DealerIDField;
    }

    public String getDividendCurrencyField() {
        return this.DividendCurrencyField;
    }
    
    public void setDividendCurrencyField(String DividendCurrencyField) {
        this.DividendCurrencyField = DividendCurrencyField;
    }

    public String getDividendTypeField() {
        return this.DividendTypeField;
    }
    
    public void setDividendTypeField(String DividendTypeField) {
        this.DividendTypeField = DividendTypeField;
    }

    public String getEntitlementPositionField() {
        return this.EntitlementPositionField;
    }
    
    public void setEntitlementPositionField(String EntitlementPositionField) {
        this.EntitlementPositionField = EntitlementPositionField;
    }

    public String getExtRef1Allowed() {
        return this.ExtRef1Allowed;
    }
    
    public void setExtRef1Allowed(String ExtRef1Allowed) {
        this.ExtRef1Allowed = ExtRef1Allowed;
    }

    public String getExtRef1Field() {
        return this.ExtRef1Field;
    }
    
    public void setExtRef1Field(String ExtRef1Field) {
        this.ExtRef1Field = ExtRef1Field;
    }

    public String getExtRef2Allowed() {
        return this.ExtRef2Allowed;
    }
    
    public void setExtRef2Allowed(String ExtRef2Allowed) {
        this.ExtRef2Allowed = ExtRef2Allowed;
    }

    public String getExtRef2Field() {
        return this.ExtRef2Field;
    }
    
    public void setExtRef2Field(String ExtRef2Field) {
        this.ExtRef2Field = ExtRef2Field;
    }

    public String getFXRateField() {
        return this.FXRateField;
    }
    
    public void setFXRateField(String FXRateField) {
        this.FXRateField = FXRateField;
    }

    public String getFrankingCreditField() {
        return this.FrankingCreditField;
    }
    
    public void setFrankingCreditField(String FrankingCreditField) {
        this.FrankingCreditField = FrankingCreditField;
    }

    public String getFrankingCreditTypeField() {
        return this.FrankingCreditTypeField;
    }
    
    public void setFrankingCreditTypeField(String FrankingCreditTypeField) {
        this.FrankingCreditTypeField = FrankingCreditTypeField;
    }

    public String getHoldingTypeAllowed() {
        return this.HoldingTypeAllowed;
    }
    
    public void setHoldingTypeAllowed(String HoldingTypeAllowed) {
        this.HoldingTypeAllowed = HoldingTypeAllowed;
    }

    public String getHoldingTypeField() {
        return this.HoldingTypeField;
    }
    
    public void setHoldingTypeField(String HoldingTypeField) {
        this.HoldingTypeField = HoldingTypeField;
    }

    public Boolean getIsEditable() {
        return this.IsEditable;
    }
    
    public void setIsEditable(Boolean IsEditable) {
        this.IsEditable = IsEditable;
    }

    public String getLotNoField() {
        return this.LotNoField;
    }
    
    public void setLotNoField(String LotNoField) {
        this.LotNoField = LotNoField;
    }

    public String getMaturityDateField() {
        return this.MaturityDateField;
    }
    
    public void setMaturityDateField(String MaturityDateField) {
        this.MaturityDateField = MaturityDateField;
    }

    public String getNominalField() {
        return this.NominalField;
    }
    
    public void setNominalField(String NominalField) {
        this.NominalField = NominalField;
    }

    public String getOpenCashField() {
        return this.OpenCashField;
    }
    
    public void setOpenCashField(String OpenCashField) {
        this.OpenCashField = OpenCashField;
    }

    public String getOpenStockField() {
        return this.OpenStockField;
    }
    
    public void setOpenStockField(String OpenStockField) {
        this.OpenStockField = OpenStockField;
    }

    public String getOrderIDField() {
        return this.OrderIDField;
    }
    
    public void setOrderIDField(String OrderIDField) {
        this.OrderIDField = OrderIDField;
    }

    public String getPaymentBasisField() {
        return this.PaymentBasisField;
    }
    
    public void setPaymentBasisField(String PaymentBasisField) {
        this.PaymentBasisField = PaymentBasisField;
    }

    public java.math.BigDecimal getPriceAllowed() {
        return this.PriceAllowed;
    }
    
    public void setPriceAllowed(java.math.BigDecimal PriceAllowed) {
        this.PriceAllowed = PriceAllowed;
    }

    public String getPriceField() {
        return this.PriceField;
    }
    
    public void setPriceField(String PriceField) {
        this.PriceField = PriceField;
    }

    public String getRegistrationField() {
        return this.RegistrationField;
    }
    
    public void setRegistrationField(String RegistrationField) {
        this.RegistrationField = RegistrationField;
    }

    public String getRepoAmountField() {
        return this.RepoAmountField;
    }
    
    public void setRepoAmountField(String RepoAmountField) {
        this.RepoAmountField = RepoAmountField;
    }

    public String getRepoAssetField() {
        return this.RepoAssetField;
    }
    
    public void setRepoAssetField(String RepoAssetField) {
        this.RepoAssetField = RepoAssetField;
    }

    public String getRwtCustodianField() {
        return this.RwtCustodianField;
    }
    
    public void setRwtCustodianField(String RwtCustodianField) {
        this.RwtCustodianField = RwtCustodianField;
    }

    public String getRwtRegistryField() {
        return this.RwtRegistryField;
    }
    
    public void setRwtRegistryField(String RwtRegistryField) {
        this.RwtRegistryField = RwtRegistryField;
    }

    public String getSalesTaxField() {
        return this.SalesTaxField;
    }
    
    public void setSalesTaxField(String SalesTaxField) {
        this.SalesTaxField = SalesTaxField;
    }

    public String getSettleCcyAllowed() {
        return this.SettleCcyAllowed;
    }
    
    public void setSettleCcyAllowed(String SettleCcyAllowed) {
        this.SettleCcyAllowed = SettleCcyAllowed;
    }

    public String getSettleCurrencyAllowed() {
        return this.SettleCurrencyAllowed;
    }
    
    public void setSettleCurrencyAllowed(String SettleCurrencyAllowed) {
        this.SettleCurrencyAllowed = SettleCurrencyAllowed;
    }

    public String getSettleCurrencyField() {
        return this.SettleCurrencyField;
    }
    
    public void setSettleCurrencyField(String SettleCurrencyField) {
        this.SettleCurrencyField = SettleCurrencyField;
    }

    public String getSettleDateField() {
        return this.SettleDateField;
    }
    
    public void setSettleDateField(String SettleDateField) {
        this.SettleDateField = SettleDateField;
    }

    public String getStampDutyField() {
        return this.StampDutyField;
    }
    
    public void setStampDutyField(String StampDutyField) {
        this.StampDutyField = StampDutyField;
    }

    public String getTradeDateField() {
        return this.TradeDateField;
    }
    
    public void setTradeDateField(String TradeDateField) {
        this.TradeDateField = TradeDateField;
    }

    public String getTransStatusAllowed() {
        return this.TransStatusAllowed;
    }
    
    public void setTransStatusAllowed(String TransStatusAllowed) {
        this.TransStatusAllowed = TransStatusAllowed;
    }

    public String getTransStatusField() {
        return this.TransStatusField;
    }
    
    public void setTransStatusField(String TransStatusField) {
        this.TransStatusField = TransStatusField;
    }

    public String getTransTypeField() {
        return this.TransTypeField;
    }
    
    public void setTransTypeField(String TransTypeField) {
        this.TransTypeField = TransTypeField;
    }

    public String getTransTypesAllowed() {
        return this.TransTypesAllowed;
    }
    
    public void setTransTypesAllowed(String TransTypesAllowed) {
        this.TransTypesAllowed = TransTypesAllowed;
    }

    public String getWitholdingTaxField() {
        return this.WitholdingTaxField;
    }
    
    public void setWitholdingTaxField(String WitholdingTaxField) {
        this.WitholdingTaxField = WitholdingTaxField;
    }

    @Override
    public String toString() {
        return "TransactionUI{" +
                "AccruedInterestField='" + AccruedInterestField + '\'' +
                ", Action='" + Action + '\'' +
                ", ApplicationMoneyField='" + ApplicationMoneyField + '\'' +
                ", AssetField='" + AssetField + '\'' +
                ", BaseFXRateField='" + BaseFXRateField + '\'' +
                ", BrokerAllowed='" + BrokerAllowed + '\'' +
                ", BrokerIDField='" + BrokerIDField + '\'' +
                ", BrokerageField='" + BrokerageField + '\'' +
                ", CanCreate=" + CanCreate +
                ", CashEffectField='" + CashEffectField + '\'' +
                ", CashFXRateField='" + CashFXRateField + '\'' +
                ", ChangeReasonField='" + ChangeReasonField + '\'' +
                ", ChargesField='" + ChargesField + '\'' +
                ", CommentAllowed='" + CommentAllowed + '\'' +
                ", CommentField='" + CommentField + '\'' +
                ", CommissionField='" + CommissionField + '\'' +
                ", ConsiderationField='" + ConsiderationField + '\'' +
                ", CouponRateField='" + CouponRateField + '\'' +
                ", CustodianField='" + CustodianField + '\'' +
                ", DataProviderAllowed='" + DataProviderAllowed + '\'' +
                ", DataProviderField='" + DataProviderField + '\'' +
                ", DealerIDField='" + DealerIDField + '\'' +
                ", DividendCurrencyField='" + DividendCurrencyField + '\'' +
                ", DividendTypeField='" + DividendTypeField + '\'' +
                ", EntitlementPositionField='" + EntitlementPositionField + '\'' +
                ", ExtRef1Allowed='" + ExtRef1Allowed + '\'' +
                ", ExtRef1Field='" + ExtRef1Field + '\'' +
                ", ExtRef2Allowed='" + ExtRef2Allowed + '\'' +
                ", ExtRef2Field='" + ExtRef2Field + '\'' +
                ", FXRateField='" + FXRateField + '\'' +
                ", FrankingCreditField='" + FrankingCreditField + '\'' +
                ", FrankingCreditTypeField='" + FrankingCreditTypeField + '\'' +
                ", HoldingTypeAllowed='" + HoldingTypeAllowed + '\'' +
                ", HoldingTypeField='" + HoldingTypeField + '\'' +
                ", IsEditable=" + IsEditable +
                ", LotNoField='" + LotNoField + '\'' +
                ", MaturityDateField='" + MaturityDateField + '\'' +
                ", NominalField='" + NominalField + '\'' +
                ", OpenCashField='" + OpenCashField + '\'' +
                ", OpenStockField='" + OpenStockField + '\'' +
                ", OrderIDField='" + OrderIDField + '\'' +
                ", PaymentBasisField='" + PaymentBasisField + '\'' +
                ", PriceAllowed=" + PriceAllowed +
                ", PriceField='" + PriceField + '\'' +
                ", RegistrationField='" + RegistrationField + '\'' +
                ", RepoAmountField='" + RepoAmountField + '\'' +
                ", RepoAssetField='" + RepoAssetField + '\'' +
                ", RwtCustodianField='" + RwtCustodianField + '\'' +
                ", RwtRegistryField='" + RwtRegistryField + '\'' +
                ", SalesTaxField='" + SalesTaxField + '\'' +
                ", SettleCcyAllowed='" + SettleCcyAllowed + '\'' +
                ", SettleCurrencyAllowed='" + SettleCurrencyAllowed + '\'' +
                ", SettleCurrencyField='" + SettleCurrencyField + '\'' +
                ", SettleDateField='" + SettleDateField + '\'' +
                ", StampDutyField='" + StampDutyField + '\'' +
                ", TradeDateField='" + TradeDateField + '\'' +
                ", TransStatusAllowed='" + TransStatusAllowed + '\'' +
                ", TransStatusField='" + TransStatusField + '\'' +
                ", TransTypeField='" + TransTypeField + '\'' +
                ", TransTypesAllowed='" + TransTypesAllowed + '\'' +
                ", WitholdingTaxField='" + WitholdingTaxField + '\'' +
                '}';
    }
}